(() => {
  const cfg = window.BDJ_AGENDA_CONFIG || {};
  const catalog = window.BDJ_SERVICES || [];
  const page = document.body.dataset.adminPage || 'dashboard';
  const $ = (id) => document.getElementById(id);
  const sb = (cfg.supabaseUrl && cfg.supabaseAnonKey) ? window.supabase.createClient(cfg.supabaseUrl, cfg.supabaseAnonKey) : null;
  let session=null, allBookings=[], customerProfiles=[], customers=[];
  let selectedDate=isoLocal(new Date()), calendarMonth=new Date(); calendarMonth.setDate(1);
  function isoLocal(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
  function formatDate(s,opts={weekday:'long',day:'2-digit',month:'long'}){return new Date(s+'T12:00:00').toLocaleDateString('pt-BR',opts)}
  function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
  function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function phoneDigits(s=''){return String(s).replace(/\D/g,'')}
  function formatPhone(p=''){p=phoneDigits(p);return p.length===11?`(${p.slice(0,2)}) ${p.slice(2,7)}-${p.slice(7)}`:p}
  function statusLabel(s){return({pending:'Aguardando',confirmed:'Confirmado',cancelled:'Cancelado',completed:'Concluído',no_show:'Ausência'})[s]||s}
  function statusClass(s){return `status-${s||'pending'}`}
  function ageFromBirth(date){if(!date)return null;const b=new Date(date+'T12:00:00'),t=new Date();let a=t.getFullYear()-b.getFullYear();const m=t.getMonth()-b.getMonth();if(m<0||(m===0&&t.getDate()<b.getDate()))a--;return a>=0?a:null}
  function birthdayLabel(date){if(!date)return '';const d=new Date(date+'T12:00:00');return d.toLocaleDateString('pt-BR',{day:'2-digit',month:'long'})}
  function daysUntilBirthday(date){if(!date)return null;const b=new Date(date+'T12:00:00'),t=new Date();t.setHours(0,0,0,0);let n=new Date(t.getFullYear(),b.getMonth(),b.getDate());if(n<t)n=new Date(t.getFullYear()+1,b.getMonth(),b.getDate());return Math.round((n-t)/86400000)}
  function friendlyDb(s=''){if(s.includes('indisponível')||s.includes('conflito'))return 'Esse período já está ocupado. Escolha outro horário.';if(s.includes('bloqueado'))return 'Esse horário está bloqueado.';return s}
  function setText(id,val){if($(id))$(id).textContent=val}
  function emailLink(x){if(!x.customer_email)return '';const subject=`Agendamento Barbearia do Ju — ${x.booking_date.split('-').reverse().join('/')} às ${x.start_time.slice(0,5)}`;const body=`Olá, ${x.customer_name}!%0D%0A%0D%0AEntramos em contato sobre seu agendamento na Barbearia do Ju em ${x.booking_date.split('-').reverse().join('/')} às ${x.start_time.slice(0,5)}.%0D%0A%0D%0AAtenciosamente,%0D%0ABarbearia do Ju`;return `mailto:${encodeURIComponent(x.customer_email)}?subject=${encodeURIComponent(subject)}&body=${body}`}
  function whatsappLink(x,type='confirm'){const when=formatDate(x.booking_date,{weekday:'long',day:'2-digit',month:'2-digit'});const msg=type==='reminder'?`Olá, ${x.customer_name}! Lembrete do seu horário amanhã, às ${x.start_time.slice(0,5)}, na Barbearia do Ju. Pode confirmar?`:`Olá, ${x.customer_name}! Seu horário está marcado para ${when}, às ${x.start_time.slice(0,5)}, na Barbearia do Ju. Pode confirmar?`;return `https://wa.me/55${phoneDigits(x.customer_phone)}?text=${encodeURIComponent(msg)}`}
  function parseProducts(x){const p=Array.isArray(x.selected_products)?x.selected_products:[];return p.filter(i=>i&&i.name)}
  function productsHtml(x){const items=parseProducts(x);if(!items.length)return '';return `<div class="admin-products"><span class="admin-products-label">🛍 Produtos reservados</span>${items.map(p=>`<span class="admin-product-chip"><b>${esc(p.name)}</b><small>${money(p.price)}</small></span>`).join('')}<strong class="admin-products-total">${money(x.products_price||items.reduce((a,p)=>a+Number(p.price||0),0))}</strong></div>`}
  async function init(){bindGlobal();if(!sb){showLogin('Configuração do Supabase ausente.');return}const {data,error}=await sb.auth.getSession();if(error){showLogin(error.message);return}session=data.session;renderAuth();sb.auth.onAuthStateChange((_e,s)=>{session=s;renderAuth()})}
  function bindGlobal(){$('admin-signin')?.addEventListener('click',signIn);$('admin-signout')?.addEventListener('click',async()=>{await sb.auth.signOut()});document.querySelectorAll('[data-admin-nav]').forEach(a=>{if(a.dataset.adminNav===page)a.classList.add('is-active')})}
  async function signIn(){const msg=$('admin-message');msg.textContent='Entrando...';const {error}=await sb.auth.signInWithPassword({email:$('admin-email').value,password:$('admin-password').value});msg.textContent=error?(error.message.includes('Invalid login')?'E-mail ou senha incorretos.':error.message):''}
  function showLogin(msg=''){$('admin-login').hidden=false;$('admin-app').hidden=true;if($('admin-message'))$('admin-message').textContent=msg}
  async function renderAuth(){if(!session){showLogin();return}$('admin-login').hidden=true;$('admin-app').hidden=false;await loadBaseData();if(page==='dashboard')renderDashboard();if(page==='agenda')initAgenda();if(page==='clientes')initCRM();if(page==='agendamento')initBookingForm()}
  async function loadBaseData(){const [{data:b,error:be},{data:p,error:pe}]=await Promise.all([sb.from('bookings').select('*').order('booking_date',{ascending:false}).order('start_time',{ascending:false}).limit(3000),sb.from('customer_profiles').select('*').order('name',{ascending:true})]);if(be){console.error(be);allBookings=[]}else allBookings=b||[];if(pe){console.error(pe);customerProfiles=[]}else customerProfiles=p||[];customers=aggregateCustomers(allBookings,customerProfiles)}
  function aggregateCustomers(rows,profiles){const profileByPhone=new Map(profiles.map(p=>[phoneDigits(p.phone),p]));const map=new Map();profiles.filter(p=>!p.archived).forEach(p=>map.set(phoneDigits(p.phone),{id:p.id,phone:phoneDigits(p.phone),name:p.name,email:p.email||'',notes:p.notes||'',birthDate:p.birth_date||null,visits:0,completed:0,noShows:0,total:0,lastDate:null,lastServices:'',history:[]}));rows.forEach(x=>{const ph=phoneDigits(x.customer_phone);if(!ph)return;const profile=profileByPhone.get(ph);if(profile?.archived)return;if(!map.has(ph))map.set(ph,{id:profile?.id||null,phone:ph,name:profile?.name||x.customer_name,email:profile?.email||x.customer_email||'',notes:profile?.notes||'',birthDate:profile?.birth_date||null,visits:0,completed:0,noShows:0,total:0,lastDate:x.booking_date,lastServices:x.service_name,history:[]});const c=map.get(ph);c.history.push(x);c.visits++;if(x.status==='completed'){c.completed++;c.total+=Number(x.service_price||0)+Number(x.products_price||0)}if(x.status==='no_show')c.noShows++;if(!c.lastDate||x.booking_date>c.lastDate){c.lastDate=x.booking_date;c.lastServices=x.service_name;if(!profile)c.name=x.customer_name;if(!c.email)c.email=x.customer_email||''}});return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'))}
  function renderDashboard(){const today=isoLocal(new Date()),tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);const tmr=isoLocal(tomorrow),todayRows=allBookings.filter(x=>x.booking_date===today),tomorrowRows=allBookings.filter(x=>x.booking_date===tmr&&['pending','confirmed'].includes(x.status)),completed=todayRows.filter(x=>x.status==='completed');setText('metric-today',todayRows.filter(x=>x.status!=='cancelled').length);setText('metric-pending',todayRows.filter(x=>x.status==='pending').length);setText('metric-confirmed',todayRows.filter(x=>x.status==='confirmed').length);setText('metric-revenue',money(completed.reduce((a,x)=>a+Number(x.service_price||0)+Number(x.products_price||0),0)));setText('metric-clients',customers.length);setText('metric-tomorrow',tomorrowRows.length);const list=$('dashboard-today-list'),active=todayRows.filter(x=>x.status!=='cancelled').sort((a,b)=>a.start_time.localeCompare(b.start_time));list.innerHTML=active.length?active.map(miniBooking).join(''):'<div class="admin-empty">Nenhum atendimento para hoje.</div>';const alerts=$('dashboard-alerts'),noShows=customers.filter(c=>c.noShows>0).sort((a,b)=>b.noShows-a.noShows).slice(0,5);alerts.innerHTML=noShows.length?noShows.map(c=>`<div class="admin-alert-row"><span>${esc(c.name)}</span><strong>${c.noShows} ausência${c.noShows>1?'s':''}</strong></div>`).join(''):'<div class="admin-empty">Nenhuma ausência registrada.</div>'}
  function miniBooking(x){return `<div class="admin-mini-booking"><time>${x.start_time.slice(0,5)}</time><div><strong>${esc(x.customer_name)}</strong><small>${esc(x.service_name)}${parseProducts(x).length?` • 🛍 ${parseProducts(x).length} produto(s)`:''}</small></div><span class="admin-status ${statusClass(x.status)}">${statusLabel(x.status)}</span></div>`}
  function initAgenda(){selectedDate=new URLSearchParams(location.search).get('data')||isoLocal(new Date());calendarMonth=new Date(selectedDate+'T12:00:00');calendarMonth.setDate(1);$('calendar-prev').onclick=()=>{calendarMonth.setMonth(calendarMonth.getMonth()-1);renderCalendar()};$('calendar-next').onclick=()=>{calendarMonth.setMonth(calendarMonth.getMonth()+1);renderCalendar()};$('block-all-day').onchange=()=>{$('block-time-fields').hidden=$('block-all-day').checked};$('block-save').onclick=saveBlock;renderCalendar();loadAgendaDay()}
  function renderCalendar(){setText('calendar-title',calendarMonth.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}));const grid=$('calendar-grid'),y=calendarMonth.getFullYear(),m=calendarMonth.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=(first.getDay()+6)%7;let html=['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(d=>`<span class="calendar-weekday">${d}</span>`).join('');for(let i=0;i<start;i++)html+='<span class="calendar-day is-empty"></span>';for(let d=1;d<=last.getDate();d++){const dt=new Date(y,m,d),ds=isoLocal(dt),count=allBookings.filter(x=>x.booking_date===ds&&x.status!=='cancelled').length;html+=`<button class="calendar-day ${ds===selectedDate?'is-selected':''} ${ds===isoLocal(new Date())?'is-today':''}" data-date="${ds}"><span>${d}</span>${count?`<small>${count}</small>`:''}</button>`}grid.innerHTML=html;grid.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.date;renderCalendar();loadAgendaDay()})}
  async function loadAgendaDay(){setText('agenda-date-title',formatDate(selectedDate));const rows=allBookings.filter(x=>x.booking_date===selectedDate).sort((a,b)=>a.start_time.localeCompare(b.start_time)),list=$('agenda-day-list');list.innerHTML=rows.length?rows.map(bookingCard).join(''):'<div class="admin-empty">Nenhum agendamento nesta data.</div>';bindBookingActions(list);await loadBlocks()}
  function bookingCard(x){const email=x.customer_email?`<a class="admin-contact-link" href="${emailLink(x)}">✉ ${esc(x.customer_email)}</a>`:'';return `<article class="admin-booking-card ${statusClass(x.status)}"><div class="admin-booking-time"><strong>${x.start_time.slice(0,5)}</strong><small>até ${x.end_time?.slice(0,5)||''}</small></div><div class="admin-booking-main"><div class="admin-booking-title"><h3>${esc(x.customer_name)}</h3><span class="admin-status ${statusClass(x.status)}">${statusLabel(x.status)}</span></div><p>${esc(x.service_name)}</p><small>${formatPhone(x.customer_phone)} • ${money(Number(x.service_price||0)+Number(x.products_price||0))} • ${x.duration_minutes} min</small>${email}${productsHtml(x)}${x.notes?`<em>${esc(x.notes)}</em>`:''}</div><div class="admin-booking-actions"><a href="${whatsappLink(x)}" target="_blank" rel="noopener">WhatsApp</a>${x.customer_email?`<a href="${emailLink(x)}">E-mail</a>`:''}${x.status==='pending'?`<button data-status="confirmed" data-id="${x.id}">Confirmar</button>`:''}${['pending','confirmed'].includes(x.status)?`<button data-reschedule="${x.id}">Remarcar</button><button data-status="completed" data-id="${x.id}">Concluir</button><button data-status="no_show" data-id="${x.id}">Ausência</button><button class="is-danger" data-status="cancelled" data-id="${x.id}">Cancelar</button>`:''}<button data-return="${x.id}">Novo retorno</button></div></article>`}
  function bindBookingActions(root){root.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>setStatus(b.dataset.id,b.dataset.status));root.querySelectorAll('[data-reschedule]').forEach(b=>b.onclick=()=>{sessionStorage.setItem('bdj-reschedule-id',b.dataset.reschedule);location.href='admin-agendamento.html?modo=remarcar'});root.querySelectorAll('[data-return]').forEach(b=>b.onclick=()=>{const x=allBookings.find(r=>r.id===b.dataset.return);prefillReturnStorage(x);location.href='admin-agendamento.html?modo=retorno'})}
  async function setStatus(id,status){const prompts={completed:'Marcar como concluído?',no_show:'Registrar ausência?',cancelled:'Cancelar e liberar o horário?'};if(prompts[status]&&!confirm(prompts[status]))return;const {error}=await sb.from('bookings').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error){alert(error.message);return}await loadBaseData();renderCalendar();loadAgendaDay()}
  async function loadBlocks(){const box=$('agenda-block-list'),{data,error}=await sb.from('schedule_blocks').select('*').eq('block_date',selectedDate).order('start_time',{ascending:true,nullsFirst:true});if(error){box.innerHTML=`<div class="admin-empty">${esc(error.message)}</div>`;return}box.innerHTML=(data||[]).length?data.map(x=>`<div class="admin-block-row"><div><strong>${x.all_day?'Dia inteiro':`${x.start_time.slice(0,5)}–${x.end_time.slice(0,5)}`}</strong><small>${esc(x.reason||'Bloqueio administrativo')}</small></div><button data-delete-block="${x.id}">Liberar</button></div>`).join(''):'<div class="admin-empty">Nenhum bloqueio nesta data.</div>';box.querySelectorAll('[data-delete-block]').forEach(b=>b.onclick=()=>deleteBlock(b.dataset.deleteBlock))}
  async function saveBlock(){const allDay=$('block-all-day').checked,start=$('block-start').value,end=$('block-end').value,msg=$('block-message');if(!allDay&&(!start||!end||start>=end)){msg.textContent='Informe um intervalo válido.';return}msg.textContent='Salvando...';const {error}=await sb.from('schedule_blocks').insert({block_date:selectedDate,all_day:allDay,start_time:allDay?null:start,end_time:allDay?null:end,reason:$('block-reason').value.trim()||null});msg.textContent=error?error.message:'Bloqueio criado.';if(!error){$('block-reason').value='';await loadBlocks()}}
  async function deleteBlock(id){if(!confirm('Liberar este bloqueio?'))return;const {error}=await sb.from('schedule_blocks').delete().eq('id',id);if(error)alert(error.message);else loadBlocks()}
  function initCRM(){$('crm-search').oninput=renderCRM;$('crm-add-customer').onclick=()=>openCustomerModal();document.querySelectorAll('[data-close-customer-modal]').forEach(x=>x.onclick=closeCustomerModal);$('crm-customer-save').onclick=saveCustomer;renderBirthdaySummary();renderCRM()}
  function renderBirthdaySummary(){
    const withBirth=customers.filter(c=>c.birthDate),today=withBirth.filter(c=>daysUntilBirthday(c.birthDate)===0),week=withBirth.filter(c=>{const d=daysUntilBirthday(c.birthDate);return d!==null&&d<=7}),month=withBirth.filter(c=>{const b=new Date(c.birthDate+'T12:00:00'),t=new Date();return b.getMonth()===t.getMonth()});
    setText('crm-birthday-today',today.length);setText('crm-birthday-week',week.length);setText('crm-birthday-month',month.length);
    const box=$('crm-birthday-list');if(box){const next=withBirth.map(c=>({...c,days:daysUntilBirthday(c.birthDate)})).sort((a,b)=>a.days-b.days).slice(0,6);box.innerHTML=next.length?next.map(c=>`<span><strong>${esc(c.name)}</strong><small>${c.days===0?'Hoje':c.days===1?'Amanhã':`em ${c.days} dias`} • ${birthdayLabel(c.birthDate)}</small></span>`).join(''):'<small>Nenhuma data de nascimento cadastrada.</small>'}
  }
  function renderCRM(){const q=($('crm-search').value||'').trim().toLowerCase(),rows=customers.filter(c=>!q||c.name.toLowerCase().includes(q)||c.phone.includes(phoneDigits(q))||(c.email||'').toLowerCase().includes(q));setText('crm-count',rows.length);const box=$('crm-list');box.innerHTML=rows.length?rows.map(customerCard).join(''):'<div class="admin-empty">Nenhum cliente encontrado.</div>';box.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>toggleCustomerHistory(b.dataset.history));box.querySelectorAll('[data-book-customer]').forEach(b=>b.onclick=()=>{const c=customers.find(x=>x.phone===b.dataset.bookCustomer);sessionStorage.setItem('bdj-prefill-customer',JSON.stringify(c));location.href='admin-agendamento.html?modo=retorno'});box.querySelectorAll('[data-edit-customer]').forEach(b=>b.onclick=()=>openCustomerModal(customers.find(x=>x.phone===b.dataset.editCustomer)));box.querySelectorAll('[data-delete-customer]').forEach(b=>b.onclick=()=>archiveCustomer(b.dataset.deleteCustomer))}
  function customerCard(c){const last=c.lastDate?formatDate(c.lastDate,{day:'2-digit',month:'2-digit',year:'numeric'}):'Sem atendimento';const email=c.email?`<a href="mailto:${encodeURIComponent(c.email)}">${esc(c.email)}</a>`:'<span>Sem e-mail</span>';const age=ageFromBirth(c.birthDate),birth=c.birthDate?`${birthdayLabel(c.birthDate)}${age!==null?` • ${age} anos`:''}`:'Nascimento não informado';return `<article class="crm-card"><div class="crm-avatar">${esc(c.name.charAt(0).toUpperCase())}</div><div class="crm-main"><h3>${esc(c.name)}</h3><p>${formatPhone(c.phone)} • ${email}</p><p class="crm-birth">🎂 ${esc(birth)}</p>${c.notes?`<p class="crm-notes">${esc(c.notes)}</p>`:''}<div class="crm-stats"><span><strong>${c.completed}</strong> atendimentos</span><span><strong>${money(c.total)}</strong> gasto</span><span><strong>${c.noShows}</strong> ausências</span><span><strong>${last}</strong> última visita</span></div><div id="crm-history-${c.phone}" class="crm-history" hidden>${c.history.length?c.history.slice(0,30).map(x=>`<div><span>${formatDate(x.booking_date,{day:'2-digit',month:'2-digit',year:'numeric'})} • ${x.start_time.slice(0,5)}</span><strong>${esc(x.service_name)}${parseProducts(x).length?` + ${parseProducts(x).map(p=>esc(p.name)).join(', ')}`:''}</strong><small>${statusLabel(x.status)} • ${money(Number(x.service_price||0)+Number(x.products_price||0))}</small></div>`).join(''):'<div class="admin-empty">Cliente cadastrado manualmente, sem histórico.</div>'}</div></div><div class="crm-actions"><button data-history="${c.phone}">Histórico</button><button data-edit-customer="${c.phone}">Editar</button><button class="is-primary" data-book-customer="${c.phone}">Agendar</button><a href="https://wa.me/55${c.phone}" target="_blank" rel="noopener">WhatsApp</a>${c.email?`<a href="mailto:${encodeURIComponent(c.email)}">E-mail</a>`:''}<button class="is-danger" data-delete-customer="${c.id||''}" ${c.id?'':'disabled'}>Excluir</button></div></article>`}
  function toggleCustomerHistory(phone){const el=$(`crm-history-${phone}`);if(el)el.hidden=!el.hidden}
  function openCustomerModal(c=null){$('crm-customer-modal').hidden=false;document.body.classList.add('modal-open');$('crm-modal-title').textContent=c?'Editar cliente':'Adicionar cliente';$('crm-customer-id').value=c?.id||'';$('crm-customer-name').value=c?.name||'';$('crm-customer-phone').value=c?.phone||'';$('crm-customer-email').value=c?.email||'';$('crm-customer-birth').value=c?.birthDate||'';$('crm-customer-notes').value=c?.notes||'';$('crm-customer-message').textContent='';setTimeout(()=>$('crm-customer-name').focus(),50)}
  function closeCustomerModal(){$('crm-customer-modal').hidden=true;document.body.classList.remove('modal-open')}
  async function saveCustomer(){const id=$('crm-customer-id').value||null,name=$('crm-customer-name').value.trim(),phone=phoneDigits($('crm-customer-phone').value),email=$('crm-customer-email').value.trim().toLowerCase()||null,birth=$('crm-customer-birth').value||null,notes=$('crm-customer-notes').value.trim()||null,msg=$('crm-customer-message');if(name.length<2||phone.length<10){msg.textContent='Informe nome e WhatsApp válidos.';return}msg.textContent='Salvando...';const {error}=await sb.rpc('admin_save_customer',{p_customer_id:id,p_name:name,p_phone:phone,p_email:email,p_birth_date:birth,p_notes:notes});if(error){msg.textContent=friendlyDb(error.message);return}await loadBaseData();closeCustomerModal();renderBirthdaySummary();renderCRM()}
  async function archiveCustomer(id){if(!id)return;if(!confirm('Excluir este cliente do CRM? O histórico de agendamentos será preservado.'))return;const {error}=await sb.rpc('admin_archive_customer',{p_customer_id:id});if(error){alert(error.message);return}await loadBaseData();renderCRM()}
  function initBookingForm(){$('booking-services').innerHTML=renderServicePicker();const dl=$('booking-customer-list');dl.innerHTML=customers.map(c=>`<option value="${esc(c.name)}" data-phone="${c.phone}"></option>`).join('');$('booking-name').oninput=fillKnownCustomer;$('booking-phone').oninput=fillKnownCustomer;$('booking-save').onclick=saveBooking;$('booking-date').value=isoLocal(new Date());$('booking-time').value='08:00';const mode=new URLSearchParams(location.search).get('modo');if(mode==='remarcar')loadRescheduleForm();else loadPrefillForm()}
  function renderServicePicker(){const groups={};catalog.forEach(s=>(groups[s.category]??=[]).push(s));return Object.entries(groups).map(([cat,items])=>`<section class="booking-service-group"><h3>${esc(cat)}</h3><div>${items.map(s=>`<label class="booking-service-option"><input type="checkbox" name="booking-service" value="${esc(s.id)}"><span><strong>${esc(s.name)}</strong><small>${s.duration} min • ${money(s.price)}</small><i>✓</i></span></label>`).join('')}</div></section>`).join('')}
  function fillKnownCustomer(){const n=$('booking-name').value.trim().toLowerCase(),p=phoneDigits($('booking-phone').value),c=customers.find(x=>x.phone===p||x.name.toLowerCase()===n);if(c){$('booking-name').value=c.name;$('booking-phone').value=c.phone}}
  function selectedServices(){return [...document.querySelectorAll('input[name="booking-service"]:checked')].map(i=>catalog.find(s=>s.id===i.value)).filter(Boolean)}
  function selectServicesByNames(text=''){const names=text.split(' + ').map(s=>s.trim());document.querySelectorAll('input[name="booking-service"]').forEach(i=>{const s=catalog.find(x=>x.id===i.value);i.checked=!!s&&names.includes(s.name)})}
  function prefillReturnStorage(x){if(!x)return;const d=new Date(x.booking_date+'T12:00:00');d.setDate(d.getDate()+15);sessionStorage.setItem('bdj-prefill-booking',JSON.stringify({name:x.customer_name,phone:x.customer_phone,date:isoLocal(d),time:x.start_time.slice(0,5),services:x.service_name,notes:'Retorno'}))}
  function loadPrefillForm(){const raw=sessionStorage.getItem('bdj-prefill-booking'),cRaw=sessionStorage.getItem('bdj-prefill-customer');if(raw){const x=JSON.parse(raw);fillForm(x);sessionStorage.removeItem('bdj-prefill-booking')}else if(cRaw){const c=JSON.parse(cRaw);fillForm({name:c.name,phone:c.phone,date:isoLocal(new Date()),time:'08:00',services:c.lastServices,notes:'Retorno'});sessionStorage.removeItem('bdj-prefill-customer')}}
  function fillForm(x){$('booking-name').value=x.name||'';$('booking-phone').value=x.phone||'';$('booking-date').value=x.date||isoLocal(new Date());$('booking-time').value=x.time||'08:00';$('booking-notes').value=x.notes||'';selectServicesByNames(x.services||'')}
  async function loadRescheduleForm(){const id=sessionStorage.getItem('bdj-reschedule-id');if(!id)return;const x=allBookings.find(r=>r.id===id);if(!x)return;$('booking-id').value=x.id;setText('booking-page-title','Remarcar agendamento');setText('booking-save-label','Salvar remarcação');fillForm({name:x.customer_name,phone:x.customer_phone,date:x.booking_date,time:x.start_time.slice(0,5),services:x.service_name,notes:x.notes||''});$('booking-name').disabled=true;$('booking-phone').disabled=true}
  async function saveBooking(){const services=selectedServices(),msg=$('booking-message');if(!$('booking-name').value.trim()||phoneDigits($('booking-phone').value).length<10||!services.length){msg.textContent='Informe cliente, WhatsApp e ao menos um serviço.';return}const base={p_booking_date:$('booking-date').value,p_start_time:$('booking-time').value,p_service_name:services.map(s=>s.name).join(' + '),p_service_price:services.reduce((a,s)=>a+s.price,0),p_duration_minutes:services.reduce((a,s)=>a+s.duration,0),p_notes:$('booking-notes').value||null};msg.textContent='Salvando...';let error;if($('booking-id').value)({error}=await sb.rpc('admin_reschedule_booking',{p_booking_id:$('booking-id').value,...base}));else({error}=await sb.rpc('admin_create_booking',{p_customer_name:$('booking-name').value.trim(),p_customer_phone:$('booking-phone').value,...base}));if(error){msg.textContent=friendlyDb(error.message);return}msg.textContent=$('booking-id').value?'Agendamento remarcado.':'Agendamento criado.';setTimeout(()=>location.href=`admin-agenda.html?data=${$('booking-date').value}`,700)}
  init();
})();