(() => {
const cfg=window.BDJ_AGENDA_CONFIG||{}; const ok=cfg.supabaseUrl&&cfg.supabaseAnonKey; const $=id=>document.getElementById(id); const sb=ok?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
const date=$('admin-date'); const now=new Date(); date.value=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
async function session(){if(!ok){$('admin-message').textContent='Preencha agenda-config.js com as chaves do Supabase.';return}const {data,error}=await sb.auth.getSession();if(error)$('admin-message').textContent=error.message;renderAuth(data?.session)}
function renderAuth(s){$('admin-login').hidden=!!s;$('admin-panel').hidden=!s;if(s)loadAll()}
$('admin-signin').onclick=async()=>{if(!ok)return session();$('admin-message').textContent='Entrando...';const {error}=await sb.auth.signInWithPassword({email:$('admin-email').value,password:$('admin-password').value});$('admin-message').textContent=error?friendlyError(error.message):'';if(!error)renderAuth(true)};
$('admin-signout').onclick=async()=>{await sb.auth.signOut();renderAuth(false)};date.onchange=loadAll;
$('block-all-day').onchange=()=>{$('block-time-fields').classList.toggle('is-disabled',$('block-all-day').checked);$('block-start').disabled=$('block-all-day').checked;$('block-end').disabled=$('block-all-day').checked};
$('block-save').onclick=saveBlock;
async function loadAll(){const ds=date.value;$('admin-date-title').textContent=new Date(ds+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});await Promise.all([loadBookings(),loadBlocks()])}
async function loadBookings(){const ds=date.value;const list=$('admin-list');list.innerHTML='<div class="panel admin-empty">Carregando agenda...</div>';const {data,error}=await sb.from('bookings').select('*').eq('booking_date',ds).order('start_time');if(error){console.error(error);list.innerHTML=`<div class="panel admin-empty"><strong>Erro ao carregar a agenda.</strong><br><small>${escapeHtml(error.message)} (${escapeHtml(error.code||'sem código')})</small></div>`;$('admin-count').textContent='!';return}const active=data.filter(x=>x.status!=='cancelled');$('admin-count').textContent=String(active.length);if(!data.length){list.innerHTML='<div class="panel admin-empty">Nenhum agendamento neste dia.</div>';return}list.innerHTML=data.map(x=>`<article class="panel admin-booking status-${escapeHtml(x.status)}"><div class="admin-booking-time">${x.start_time.slice(0,5)}</div><div class="admin-booking-info"><strong>${escapeHtml(x.customer_name)}</strong><span>${escapeHtml(x.service_name)}</span><small>${x.duration_minutes} min • ${Number(x.service_price).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})} • ${statusLabel(x.status)}</small><small>${escapeHtml(x.customer_phone)}</small>${x.notes?`<small>Obs.: ${escapeHtml(x.notes)}</small>`:''}</div><div class="admin-actions"><button data-id="${x.id}" data-status="confirmed">Confirmar</button><button data-id="${x.id}" data-status="completed">Concluir</button><button data-id="${x.id}" data-status="no_show">Ausência</button><button data-id="${x.id}" data-status="cancelled">Cancelar</button><a href="https://wa.me/55${x.customer_phone.replace(/\D/g,'')}" target="_blank" rel="noopener">WhatsApp</a></div></article>`).join('');list.querySelectorAll('button[data-id]').forEach(b=>b.onclick=()=>setStatus(b.dataset.id,b.dataset.status));}
async function loadBlocks(){const ds=date.value;const box=$('admin-blocks');box.innerHTML='<p class="field-help">Carregando bloqueios...</p>';const {data,error}=await sb.from('schedule_blocks').select('*').eq('block_date',ds).order('start_time',{ascending:true,nullsFirst:true});if(error){box.innerHTML=`<p class="field-help">Erro ao carregar bloqueios: ${escapeHtml(error.message)}</p>`;return}if(!data.length){box.innerHTML='<p class="field-help">Nenhum bloqueio criado para esta data.</p>';return}box.innerHTML=data.map(x=>`<div class="admin-block-item"><div><strong>${x.all_day?'Dia inteiro':`${x.start_time.slice(0,5)}–${x.end_time.slice(0,5)}`}</strong><small>${escapeHtml(x.reason||'Bloqueio administrativo')}</small></div><button type="button" data-delete-block="${x.id}">Liberar</button></div>`).join('');box.querySelectorAll('[data-delete-block]').forEach(b=>b.onclick=()=>deleteBlock(b.dataset.deleteBlock));}
async function saveBlock(){const allDay=$('block-all-day').checked,start=$('block-start').value,end=$('block-end').value,reason=$('block-reason').value.trim();const msg=$('block-message');if(!allDay&&(!start||!end||start>=end)){msg.textContent='Informe um horário inicial e final válidos.';return}msg.textContent='Salvando bloqueio...';const payload={block_date:date.value,all_day:allDay,start_time:allDay?null:start,end_time:allDay?null:end,reason:reason||null};const {error}=await sb.from('schedule_blocks').insert(payload);if(error){msg.textContent=error.message;return}msg.textContent='Bloqueio criado com sucesso.';$('block-reason').value='';await loadBlocks();}
async function deleteBlock(id){if(!confirm('Liberar este dia ou horário novamente?'))return;const {error}=await sb.from('schedule_blocks').delete().eq('id',id);if(error)alert(error.message);else loadBlocks()}
async function setStatus(id,status){const prompts={completed:'Marcar este atendimento como concluído?',no_show:'Registrar que o cliente não compareceu?',cancelled:'Cancelar este agendamento e liberar o horário?'};if(prompts[status]&&!confirm(prompts[status]))return;const {error}=await sb.from('bookings').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else loadBookings()}
function statusLabel(s){return({pending:'Aguardando',confirmed:'Confirmado',cancelled:'Cancelado',completed:'Concluído',no_show:'Não compareceu'})[s]||s}
function friendlyError(s=''){return s.includes('Invalid login credentials')?'E-mail ou senha incorretos.':s}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
sb?.auth.onAuthStateChange((_e,s)=>renderAuth(s));session();
})();
