(() => {
const cfg=window.BDJ_AGENDA_CONFIG||{}; const ok=cfg.supabaseUrl&&cfg.supabaseAnonKey; const $=id=>document.getElementById(id); const sb=ok?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
const catalog=(window.BDJ_SERVICES||[]); const date=$('admin-date'); const now=new Date(); date.value=isoLocal(now);
let customers=[]; let customerHistory=[];
function isoLocal(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
async function session(){if(!ok){$('admin-message').textContent='Preencha agenda-config.js com as chaves do Supabase.';return}const {data,error}=await sb.auth.getSession();if(error)$('admin-message').textContent=error.message;renderAuth(data?.session)}
function renderAuth(s){$('admin-login').hidden=!!s;$('admin-panel').hidden=!s;if(s){setupForms();loadAll();loadCustomers();loadTomorrow()}}
$('admin-signin').onclick=async()=>{if(!ok)return session();$('admin-message').textContent='Entrando...';const {error}=await sb.auth.signInWithPassword({email:$('admin-email').value,password:$('admin-password').value});$('admin-message').textContent=error?friendlyError(error.message):'';if(!error)renderAuth(true)};
$('admin-signout').onclick=async()=>{await sb.auth.signOut();renderAuth(false)};date.onchange=loadAll;
$('block-all-day').onchange=()=>{$('block-time-fields').classList.toggle('is-disabled',$('block-all-day').checked);$('block-start').disabled=$('block-all-day').checked;$('block-end').disabled=$('block-all-day').checked}; $('block-save').onclick=saveBlock;
function setupForms(){if($('manual-services').children.length)return;$('manual-date').value=date.value;$('manual-time').value='08:00';$('manual-services').innerHTML=renderServiceChecks('manual-service');$('reschedule-services').innerHTML=renderServiceChecks('reschedule-service');$('manual-save').onclick=createManualBooking;$('reschedule-save').onclick=saveReschedule;$('manual-phone').addEventListener('input',fillKnownCustomer);$('manual-name').addEventListener('input',fillKnownCustomer);$('customer-search').addEventListener('input',renderCustomers)}
function renderServiceChecks(name){const groups={};catalog.forEach(s=>(groups[s.category]??=[]).push(s));return Object.entries(groups).map(([cat,items])=>`<fieldset class="admin-service-group"><legend>${escapeHtml(cat)}</legend>${items.map(s=>`<label class="admin-service-option"><input type="checkbox" name="${name}" value="${escapeHtml(s.id)}"><span><strong>${escapeHtml(s.name)}</strong><small>${s.duration} min • ${money(s.price)}</small></span></label>`).join('')}</fieldset>`).join('')}
function selectedServices(name){return [...document.querySelectorAll(`input[name="${name}"]:checked`)].map(i=>catalog.find(s=>s.id===i.value)).filter(Boolean)}
async function loadAll(){const ds=date.value;$('admin-date-title').textContent=new Date(ds+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});$('manual-date').value=ds;await Promise.all([loadBookings(),loadBlocks()])}
async function loadBookings(){const ds=date.value;const list=$('admin-list');list.innerHTML='<div class="panel admin-empty">Carregando agenda...</div>';const {data,error}=await sb.from('bookings').select('*').eq('booking_date',ds).order('start_time');if(error){list.innerHTML=`<div class="panel admin-empty"><strong>Erro ao carregar a agenda.</strong><br><small>${escapeHtml(error.message)}</small></div>`;$('admin-count').textContent='!';return}const active=data.filter(x=>x.status!=='cancelled');$('admin-count').textContent=String(active.length);if(!data.length){list.innerHTML='<div class="panel admin-empty">Nenhum agendamento neste dia.</div>';return}list.innerHTML=data.map(x=>`<article class="panel admin-booking status-${escapeHtml(x.status)}"><div class="admin-booking-time">${x.start_time.slice(0,5)}</div><div class="admin-booking-info"><strong>${escapeHtml(x.customer_name)}</strong><span>${escapeHtml(x.service_name)}</span><small>${x.duration_minutes} min • ${money(x.service_price)} • ${statusLabel(x.status)}</small><small>${escapeHtml(x.customer_phone)}</small>${x.notes?`<small>Obs.: ${escapeHtml(x.notes)}</small>`:''}</div><div class="admin-actions"><button data-id="${x.id}" data-status="confirmed">Confirmar</button><button data-reschedule='${escapeAttr(JSON.stringify(x))}'>Remarcar</button><button data-return='${escapeAttr(JSON.stringify(x))}'>Novo retorno</button><button data-id="${x.id}" data-status="completed">Concluir</button><button data-id="${x.id}" data-status="no_show">Ausência</button><button data-id="${x.id}" data-status="cancelled">Cancelar</button><a href="${whatsappLink(x,'confirm')}" target="_blank" rel="noopener">WhatsApp</a></div></article>`).join('');list.querySelectorAll('button[data-id]').forEach(b=>b.onclick=()=>setStatus(b.dataset.id,b.dataset.status));list.querySelectorAll('[data-reschedule]').forEach(b=>b.onclick=()=>openReschedule(JSON.parse(b.dataset.reschedule)));list.querySelectorAll('[data-return]').forEach(b=>b.onclick=()=>prefillReturn(JSON.parse(b.dataset.return)))}
async function loadCustomers(){const {data,error}=await sb.from('bookings').select('*').order('booking_date',{ascending:false}).order('start_time',{ascending:false}).limit(5000);if(error){$('customer-cards').innerHTML='<p class="field-help">Não foi possível carregar os clientes.</p>';return}customerHistory=data;const map=new Map();data.forEach(x=>{const p=(x.customer_phone||'').replace(/\D/g,'');if(!p)return;if(!map.has(p))map.set(p,{name:x.customer_name,phone:p,visits:0,completed:0,noShows:0,total:0,lastDate:null,lastServices:x.service_name});const c=map.get(p);c.visits++;if(x.status==='completed'){c.completed++;c.total+=Number(x.service_price)||0}if(x.status==='no_show')c.noShows++;if(!c.lastDate||x.booking_date>c.lastDate){c.lastDate=x.booking_date;c.lastServices=x.service_name;c.name=x.customer_name}});customers=[...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));$('customer-list').innerHTML=customers.map(c=>`<option value="${escapeAttr(c.name)}">${escapeHtml(c.phone)}</option>`).join('');renderCustomers()}
function renderCustomers(){const q=($('customer-search').value||'').trim().toLowerCase();const filtered=customers.filter(c=>!q||c.name.toLowerCase().includes(q)||c.phone.includes(q.replace(/\D/g,''))).slice(0,80);$('customer-summary').textContent=`${customers.length} clientes cadastrados • ${filtered.length} exibidos`;const box=$('customer-cards');if(!filtered.length){box.innerHTML='<p class="field-help">Nenhum cliente encontrado.</p>';return}box.innerHTML=filtered.map(c=>`<article class="admin-customer-card"><div><strong>${escapeHtml(c.name)}</strong><small>${formatPhone(c.phone)}</small><span>Última visita: ${c.lastDate?formatDate(c.lastDate):'—'} • Concluídos: ${c.completed} • Ausências: ${c.noShows}</span><span>Gasto registrado: ${money(c.total)}</span></div><div class="admin-customer-actions"><button type="button" data-customer-phone="${escapeAttr(c.phone)}">Ver histórico</button><button type="button" data-book-customer="${escapeAttr(c.phone)}">Agendar retorno</button><a href="https://wa.me/55${c.phone}" target="_blank" rel="noopener">WhatsApp</a></div><div class="admin-customer-history" id="history-${c.phone}" hidden></div></article>`).join('');box.querySelectorAll('[data-book-customer]').forEach(b=>b.onclick=()=>prefillCustomer(customers.find(c=>c.phone===b.dataset.bookCustomer)));box.querySelectorAll('[data-customer-phone]').forEach(b=>b.onclick=()=>toggleHistory(b.dataset.customerPhone))}
function toggleHistory(phone){const el=$(`history-${phone}`);if(!el)return;if(!el.hidden){el.hidden=true;return}const rows=customerHistory.filter(x=>(x.customer_phone||'').replace(/\D/g,'')===phone).slice(0,12);el.innerHTML=rows.map(x=>`<div class="admin-history-row"><span>${formatDate(x.booking_date)} • ${x.start_time.slice(0,5)}</span><strong>${escapeHtml(x.service_name)}</strong><small>${statusLabel(x.status)} • ${money(x.service_price)}</small></div>`).join('')||'<p class="field-help">Sem histórico.</p>';el.hidden=false}
function fillKnownCustomer(){const name=$('manual-name').value.trim().toLowerCase(),phone=$('manual-phone').value.replace(/\D/g,'');const c=customers.find(x=>x.phone===phone||x.name.toLowerCase()===name);if(c){$('manual-name').value=c.name;$('manual-phone').value=c.phone}}
function clearManualServices(){document.querySelectorAll('input[name="manual-service"]').forEach(i=>i.checked=false)}
function selectServicesByNames(text){clearManualServices();const names=(text||'').split(' + ').map(s=>s.trim());catalog.filter(s=>names.includes(s.name)).forEach(s=>{const i=document.querySelector(`input[name="manual-service"][value="${CSS.escape(s.id)}"]`);if(i)i.checked=true})}
function prefillCustomer(c){if(!c)return;$('manual-name').value=c.name;$('manual-phone').value=c.phone;$('manual-date').value=date.value;$('manual-time').value='08:00';selectServicesByNames(c.lastServices);$('manual-notes').value='Retorno agendado pelo painel';$('manual-message').textContent='Cliente preenchido. Escolha data, horário e confirme os serviços.';$('manual-name').scrollIntoView({behavior:'smooth',block:'center'})}
function prefillReturn(x){$('manual-name').value=x.customer_name;$('manual-phone').value=x.customer_phone;const d=new Date(x.booking_date+'T12:00:00');d.setDate(d.getDate()+15);$('manual-date').value=isoLocal(d);$('manual-time').value=x.start_time.slice(0,5);selectServicesByNames(x.service_name);$('manual-notes').value='Retorno';$('manual-message').textContent='Retorno preenchido para 15 dias depois. Ajuste se necessário e salve.';$('manual-name').scrollIntoView({behavior:'smooth',block:'center'})}
async function createManualBooking(){const services=selectedServices('manual-service');const msg=$('manual-message');if(!$('manual-name').value.trim()||$('manual-phone').value.replace(/\D/g,'').length<10||!services.length){msg.textContent='Informe cliente, WhatsApp e ao menos um serviço.';return}const payload={p_customer_name:$('manual-name').value.trim(),p_customer_phone:$('manual-phone').value,p_service_name:services.map(s=>s.name).join(' + '),p_service_price:services.reduce((a,s)=>a+s.price,0),p_duration_minutes:services.reduce((a,s)=>a+s.duration,0),p_booking_date:$('manual-date').value,p_start_time:$('manual-time').value,p_notes:$('manual-notes').value||null};msg.textContent='Salvando...';const {error}=await sb.rpc('admin_create_booking',payload);if(error){msg.textContent=friendlyDb(error.message);return}msg.textContent='Agendamento criado.';clearManualServices();await Promise.all([loadAll(),loadCustomers(),loadTomorrow()])}
function openReschedule(x){$('reschedule-id').value=x.id;$('reschedule-customer').textContent=`${x.customer_name} • ${x.service_name}`;$('reschedule-date').value=x.booking_date;$('reschedule-time').value=x.start_time.slice(0,5);$('reschedule-notes').value=x.notes||'';document.querySelectorAll('input[name="reschedule-service"]').forEach(i=>i.checked=false);const names=x.service_name.split(' + ').map(s=>s.trim());catalog.filter(s=>names.includes(s.name)).forEach(s=>{const i=document.querySelector(`input[name="reschedule-service"][value="${CSS.escape(s.id)}"]`);if(i)i.checked=true});$('reschedule-box').hidden=false;$('reschedule-box').scrollIntoView({behavior:'smooth',block:'center'})}
async function saveReschedule(){const services=selectedServices('reschedule-service');const msg=$('reschedule-message');if(!services.length){msg.textContent='Escolha ao menos um serviço.';return}msg.textContent='Remarcando...';const {error}=await sb.rpc('admin_reschedule_booking',{p_booking_id:$('reschedule-id').value,p_booking_date:$('reschedule-date').value,p_start_time:$('reschedule-time').value,p_service_name:services.map(s=>s.name).join(' + '),p_service_price:services.reduce((a,s)=>a+s.price,0),p_duration_minutes:services.reduce((a,s)=>a+s.duration,0),p_notes:$('reschedule-notes').value||null});if(error){msg.textContent=friendlyDb(error.message);return}msg.textContent='Agendamento remarcado.';$('reschedule-box').hidden=true;date.value=$('reschedule-date').value;await Promise.all([loadAll(),loadTomorrow(),loadCustomers()])}
async function loadTomorrow(){const d=new Date();d.setDate(d.getDate()+1);const ds=isoLocal(d);$('tomorrow-title').textContent=new Date(ds+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});const {data,error}=await sb.from('bookings').select('*').eq('booking_date',ds).in('status',['pending','confirmed']).order('start_time');const box=$('tomorrow-list');if(error){box.innerHTML='<p class="field-help">Não foi possível carregar.</p>';return}if(!data.length){box.innerHTML='<p class="field-help">Nenhum cliente agendado para amanhã.</p>';return}box.innerHTML=data.map(x=>`<div class="admin-reminder-item"><div><strong>${x.start_time.slice(0,5)} • ${escapeHtml(x.customer_name)}</strong><small>${escapeHtml(x.service_name)} • ${statusLabel(x.status)}</small></div><a href="${whatsappLink(x,'reminder')}" target="_blank" rel="noopener">Enviar lembrete</a></div>`).join('')}
function whatsappLink(x,type){const when=new Date(x.booking_date+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'2-digit'});const msg=type==='reminder'?`Olá, ${x.customer_name}! Passando para lembrar do seu horário amanhã, às ${x.start_time.slice(0,5)}, na Barbearia do Ju. Pode confirmar sua presença?`:`Olá, ${x.customer_name}! Seu agendamento para ${when}, às ${x.start_time.slice(0,5)}, foi recebido. Podemos confirmar?`;return `https://wa.me/55${x.customer_phone.replace(/\D/g,'')}?text=${encodeURIComponent(msg)}`}
async function loadBlocks(){const ds=date.value;const box=$('admin-blocks');box.innerHTML='<p class="field-help">Carregando bloqueios...</p>';const {data,error}=await sb.from('schedule_blocks').select('*').eq('block_date',ds).order('start_time',{ascending:true,nullsFirst:true});if(error){box.innerHTML=`<p class="field-help">Erro ao carregar bloqueios: ${escapeHtml(error.message)}</p>`;return}if(!data.length){box.innerHTML='<p class="field-help">Nenhum bloqueio criado para esta data.</p>';return}box.innerHTML=data.map(x=>`<div class="admin-block-item"><div><strong>${x.all_day?'Dia inteiro':`${x.start_time.slice(0,5)}–${x.end_time.slice(0,5)}`}</strong><small>${escapeHtml(x.reason||'Bloqueio administrativo')}</small></div><button type="button" data-delete-block="${x.id}">Liberar</button></div>`).join('');box.querySelectorAll('[data-delete-block]').forEach(b=>b.onclick=()=>deleteBlock(b.dataset.deleteBlock))}
async function saveBlock(){const allDay=$('block-all-day').checked,start=$('block-start').value,end=$('block-end').value,reason=$('block-reason').value.trim();const msg=$('block-message');if(!allDay&&(!start||!end||start>=end)){msg.textContent='Informe um horário inicial e final válidos.';return}msg.textContent='Salvando bloqueio...';const {error}=await sb.from('schedule_blocks').insert({block_date:date.value,all_day:allDay,start_time:allDay?null:start,end_time:allDay?null:end,reason:reason||null});if(error){msg.textContent=error.message;return}msg.textContent='Bloqueio criado com sucesso.';$('block-reason').value='';await loadBlocks()}
async function deleteBlock(id){if(!confirm('Liberar este dia ou horário novamente?'))return;const {error}=await sb.from('schedule_blocks').delete().eq('id',id);if(error)alert(error.message);else loadBlocks()}
async function setStatus(id,status){const prompts={completed:'Marcar este atendimento como concluído?',no_show:'Registrar que o cliente não compareceu?',cancelled:'Cancelar este agendamento e liberar o horário?'};if(prompts[status]&&!confirm(prompts[status]))return;const {error}=await sb.from('bookings').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else Promise.all([loadBookings(),loadTomorrow(),loadCustomers()])}
function statusLabel(s){return({pending:'Aguardando',confirmed:'Confirmado',cancelled:'Cancelado',completed:'Concluído',no_show:'Não compareceu'})[s]||s}
function friendlyError(s=''){return s.includes('Invalid login credentials')?'E-mail ou senha incorretos.':s}
function friendlyDb(s=''){if(s.includes('indisponível')||s.includes('conflito'))return 'Esse período já está ocupado. Escolha outro horário.';if(s.includes('bloqueado'))return 'Esse horário está bloqueado.';return s}
function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function formatDate(s){return new Date(s+'T12:00:00').toLocaleDateString('pt-BR')}
function formatPhone(p){return p.length===11?`(${p.slice(0,2)}) ${p.slice(2,7)}-${p.slice(7)}`:p}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function escapeAttr(s=''){return escapeHtml(s).replace(/`/g,'&#96;')}
sb?.auth.onAuthStateChange((_e,s)=>renderAuth(s));session();
})();
