(() => {
const SERVICES=window.BDJ_SERVICES||[];
const cfg=window.BDJ_AGENDA_CONFIG||{}; const configured=Boolean(cfg.supabaseUrl&&cfg.supabaseAnonKey);
const sb=configured?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
const $=id=>document.getElementById(id); let selectedTime=''; let selectedServices=[]; let fullSlots=[]; let partialSlots=[];
const date=$('agenda-date'),slots=$('agenda-slots'),status=$('agenda-status'),submit=$('agenda-submit'),servicesBox=$('agenda-services');
const pad=n=>String(n).padStart(2,'0'); const money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const today=new Date(); date.min=`${today.getFullYear()}-${pad(today.getMonth()+1)}-${pad(today.getDate())}`;
function totals(){return selectedServices.reduce((a,i)=>({price:a.price+SERVICES[i].price,duration:a.duration+SERVICES[i].duration}),{price:0,duration:0})}
function formatDuration(m){if(m<60)return `${m} min`;const h=Math.floor(m/60),r=m%60;return r?`${h}h${pad(r)}`:`${h}h`;}
function addMinutes(time,mins){const [h,m]=time.split(':').map(Number);const d=new Date(2000,0,1,h,m+mins);return `${pad(d.getHours())}:${pad(d.getMinutes())}`;}
function renderServices(){const groups={};SERVICES.forEach((s,i)=>{const c=s.category||'Outros serviços';(groups[c]||(groups[c]=[])).push({s,i});});servicesBox.innerHTML=Object.entries(groups).map(([category,items])=>`<section class="agenda-service-category"><h3>${category}</h3><div class="agenda-service-category-grid">${items.map(({s,i})=>`<button type="button" class="agenda-service-option" data-index="${i}" aria-pressed="false"><span><strong>${s.name}</strong><small>${s.description}</small><em>Tempo: ${formatDuration(s.duration)}</em></span><b>${money(s.price)}</b></button>`).join('')}</div></section>`).join('');servicesBox.querySelectorAll('button').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.index);const pos=selectedServices.indexOf(i);if(pos>=0)selectedServices.splice(pos,1);else selectedServices.push(i);b.classList.toggle('is-selected',pos<0);b.setAttribute('aria-pressed',String(pos<0));loadSlots();});}
function dayHours(ds){if(!ds)return null;const d=new Date(ds+'T12:00:00');const wd=d.getDay();if(wd===0||wd===1)return null;return wd===6?['08:00','15:00']:['08:00','19:00'];}
function showHint(html,type='info'){let box=$('agenda-slot-hint');if(!box){box=document.createElement('div');box.id='agenda-slot-hint';box.className='agenda-slot-hint';slots.before(box);}box.className=`agenda-slot-hint ${type}`;box.innerHTML=html;box.hidden=false;}
function hideHint(){const box=$('agenda-slot-hint');if(box)box.hidden=true;}
async function rpcSlots(ds,duration){const {data,error}=await sb.rpc('get_available_slots',{p_date:ds,p_duration_minutes:duration});if(error)throw error;return (data||[]).map(x=>x.slot_time.slice(0,5));}
async function loadSlots(){selectedTime='';slots.innerHTML='';hideHint();const ds=date.value;const t=totals();if(!selectedServices.length||!ds){update();return}if(!dayHours(ds)){$('agenda-day-message').textContent='Fechado neste dia.';update();return}$('agenda-day-message').textContent='Consultando disponibilidade...';try{const shortest=Math.min(...selectedServices.map(i=>SERVICES[i].duration));[fullSlots,partialSlots]=await Promise.all([rpcSlots(ds,t.duration),rpcSlots(ds,shortest)]);}catch(error){slots.innerHTML='<p>Não foi possível consultar a agenda.</p>';console.error(error);$('agenda-day-message').textContent='Erro na consulta';return}
partialSlots.forEach(tm=>{const fitsAll=fullSlots.includes(tm);const b=document.createElement('button');b.type='button';b.className=`agenda-slot${fitsAll?'':' is-partial'}`;b.innerHTML=fitsAll?tm:`${tm}<small>1 serviço</small>`;b.setAttribute('aria-pressed','false');b.onclick=()=>{document.querySelectorAll('.agenda-slot').forEach(x=>{x.classList.remove('is-selected');x.setAttribute('aria-pressed','false')});if(!fitsAll){const next=fullSlots.find(x=>x>tm);const msg=next?`Às ${tm} cabe só 1 serviço. Para todos, escolha <button type="button" data-use-slot="${next}">${next}</button>.`:`Às ${tm} cabe só 1 serviço. Remova um serviço ou escolha outro horário.`;showHint(msg,'warning');const quick=$('agenda-slot-hint').querySelector('[data-use-slot]');if(quick)quick.onclick=()=>selectSlot(next);selectedTime='';update();return}hideHint();selectSlot(tm,b);};slots.appendChild(b)});$('agenda-day-message').textContent=fullSlots.length?`${fullSlots.length} horários para todos os serviços`:'Nenhum horário comporta todos os serviços';update();}
function selectSlot(tm,button){document.querySelectorAll('.agenda-slot').forEach(x=>{x.classList.remove('is-selected');x.setAttribute('aria-pressed','false')});const b=button||[...document.querySelectorAll('.agenda-slot')].find(x=>x.textContent.trim().startsWith(tm));if(b){b.classList.add('is-selected');b.setAttribute('aria-pressed','true');}selectedTime=tm;update();}
function update(){const ds=date.value,n=$('agenda-name').value.trim(),p=$('agenda-phone').value.replace(/\D/g,''),t=totals();let html='<p>Selecione um ou mais serviços, uma data e um horário.</p>';if(selectedServices.length){html=`<ul class="agenda-summary-services">${selectedServices.map(i=>`<li>${SERVICES[i].name}<span>${money(SERVICES[i].price)}</span></li>`).join('')}</ul><p><strong>Total: ${money(t.price)}</strong><br>Tempo total: ${formatDuration(t.duration)}</p>`}if(ds)html+=`<p>${new Date(ds+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}${selectedTime?` às ${selectedTime}<br><strong>Término previsto: ${addMinutes(selectedTime,t.duration)}</strong>`:''}</p>`;$('agenda-summary').innerHTML=html;submit.disabled=!(configured&&selectedServices.length&&ds&&selectedTime&&n&&p.length>=10);}
async function save(){const t=totals();const names=selectedServices.map(i=>SERVICES[i].name);submit.disabled=true;submit.textContent='Enviando...';const phone=$('agenda-phone').value.replace(/\D/g,'');const {error}=await sb.rpc('create_public_booking',{p_customer_name:$('agenda-name').value.trim(),p_customer_phone:phone,p_service_name:names.join(' + '),p_service_price:t.price,p_duration_minutes:t.duration,p_booking_date:date.value,p_start_time:selectedTime,p_notes:$('agenda-notes').value.trim()||null});if(error){alert(error.message.includes('indisponível')||error.message.includes('bloqueado')?error.message:'Não foi possível agendar. Tente novamente.');submit.textContent='Solicitar agendamento';loadSlots();return}window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:'agendamento_proprio_solicitado',servicos:names.join(' | '),data:date.value,hora:selectedTime,valor:t.price,duracao:t.duration});status.innerHTML='<strong>Solicitação recebida!</strong> Aguarde a confirmação pelo WhatsApp.';status.scrollIntoView({behavior:'smooth'});submit.textContent='Solicitação enviada';}
date.addEventListener('change',loadSlots);['agenda-name','agenda-phone','agenda-notes'].forEach(id=>$(id).addEventListener('input',update));submit.addEventListener('click',save);renderServices();status.innerHTML=configured?'<strong>Agenda própria conectada.</strong> Escolha um ou mais serviços e um horário disponível.':'<strong>Versão de preparação.</strong> O banco de dados ainda precisa ser conectado.';update();
})();
