(() => {
const SERVICES=[{"name": "Corte Masculino", "price": 40, "duration": 45}, {"name": "Barba Express", "price": 25, "duration": 30}, {"name": "Barboterapia", "price": 40, "duration": 45}, {"name": "Corte + Barba Express", "price": 60, "duration": 60}, {"name": "Corte + Barboterapia", "price": 75, "duration": 75}, {"name": "Sobrancelha Masculina", "price": 15, "duration": 15}, {"name": "Luzes", "price": 120, "duration": 90}, {"name": "Nevou / Platinado", "price": 150, "duration": 120}, {"name": "Alisamento / Relaxamento", "price": 70, "duration": 45}, {"name": "Pigmentação Capilar", "price": 50, "duration": 30}];
const cfg=window.BDJ_AGENDA_CONFIG||{}; const configured=Boolean(cfg.supabaseUrl&&cfg.supabaseAnonKey);
const sb=configured?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
const $=id=>document.getElementById(id); let selectedTime='';
const service=$('agenda-service'), date=$('agenda-date'), slots=$('agenda-slots'), status=$('agenda-status'), submit=$('agenda-submit');
const pad=n=>String(n).padStart(2,'0'); const money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const today=new Date(); date.min=`${today.getFullYear()}-${pad(today.getMonth()+1)}-${pad(today.getDate())}`;
function dayHours(ds){ if(!ds)return null; const d=new Date(ds+'T12:00:00'); const wd=d.getDay(); if(wd===0||wd===1)return null; return wd===6?['08:30','14:00']:['08:30','18:00']; }
function mins(t){const [h,m]=t.split(':').map(Number);return h*60+m} function fmt(m){return `${pad(Math.floor(m/60))}:${pad(m%60)}`}
function candidateSlots(ds,duration){const h=dayHours(ds);if(!h)return[];let a=[];for(let m=mins(h[0]);m+duration<=mins(h[1]);m+=15)a.push(fmt(m));return a}
async function loadSlots(){selectedTime='';slots.innerHTML='';const idx=Number(service.value), ds=date.value;if(!service.value||!ds){update();return};const s=SERVICES[idx];const base=candidateSlots(ds,s.duration);if(!base.length){$('agenda-day-message').textContent='Fechado neste dia.';update();return};$('agenda-day-message').textContent=configured?'Consultando disponibilidade...':'Prévia dos horários';let busy=[];if(configured){const {data,error}=await sb.rpc('get_available_slots',{p_date:ds,p_duration_minutes:s.duration});if(error){slots.innerHTML='<p>Não foi possível consultar a agenda.</p>';console.error(error);return};busy=data||[];}const available=configured?busy.map(x=>x.slot_time.slice(0,5)):base;available.forEach(t=>{const b=document.createElement('button');b.type='button';b.className='agenda-slot';b.textContent=t;b.onclick=()=>{document.querySelectorAll('.agenda-slot').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedTime=t;update();};slots.appendChild(b)});$('agenda-day-message').textContent=available.length?`${available.length} horários`:'Sem horários disponíveis';update();}
function update(){const idx=Number(service.value), ds=date.value, n=$('agenda-name').value.trim(), p=$('agenda-phone').value.replace(/\D/g,'');const s=service.value?SERVICES[idx]:null;let html='<p>Selecione um serviço, uma data e um horário.</p>';if(s)html=`<p><strong>${s.name}</strong><br>${money(s.price)} • ${s.duration} min</p>`;if(ds)html+=`<p>${new Date(ds+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}${selectedTime?' às '+selectedTime:''}</p>`;$('agenda-summary').innerHTML=html;submit.disabled=!(configured&&s&&ds&&selectedTime&&n&&p.length>=10);}
async function save(){const idx=Number(service.value), s=SERVICES[idx];submit.disabled=true;submit.textContent='Enviando...';const phone=$('agenda-phone').value.replace(/\D/g,'');const {data,error}=await sb.rpc('create_public_booking',{p_customer_name:$('agenda-name').value.trim(),p_customer_phone:phone,p_service_name:s.name,p_service_price:s.price,p_duration_minutes:s.duration,p_booking_date:date.value,p_start_time:selectedTime,p_notes:$('agenda-notes').value.trim()||null});if(error){alert(error.message.includes('indisponível')?error.message:'Não foi possível agendar. Tente novamente.');submit.textContent='Solicitar agendamento';loadSlots();return};window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:'agendamento_proprio_solicitado',servico:s.name,data:date.value,hora:selectedTime});status.innerHTML='<strong>Solicitação recebida!</strong> Aguarde a confirmação pelo WhatsApp.';status.scrollIntoView({behavior:'smooth'});submit.textContent='Solicitação enviada';}
[service,date].forEach(x=>x.addEventListener('change',loadSlots));['agenda-name','agenda-phone','agenda-notes'].forEach(id=>$(id).addEventListener('input',update));submit.addEventListener('click',save);if(configured){status.innerHTML='<strong>Agenda própria conectada.</strong> Escolha um horário disponível.';} else {status.innerHTML='<strong>Versão de preparação.</strong> O banco de dados ainda precisa ser conectado antes da publicação.';}update();
})();