(()=>{
  const cfg=window.BDJ_AGENDA_CONFIG||{};
  if(!cfg.supabaseUrl||!cfg.supabaseAnonKey)return;
  const endpoint=`${cfg.supabaseUrl}/functions/v1/ju-ia-site`;
  const WA='https://wa.me/5511967073038?text='+encodeURIComponent('Olá, vim pelo atendimento da JuIA no site e prefiro falar diretamente com o Juliano.');
  const sid=sessionStorage.getItem('bdj_juia_sid')||crypto.randomUUID();sessionStorage.setItem('bdj_juia_sid',sid);
  let state=JSON.parse(sessionStorage.getItem('bdj_juia_state')||'{}');
  let history=JSON.parse(sessionStorage.getItem('bdj_juia_history')||'[]');
  const html=`<button class="juia-launcher" aria-label="Conversar com a JuIA"><span>💈</span><span>Conversar com a JuIA</span></button><section class="juia-chat" role="dialog" aria-label="Atendimento virtual Barbearia do Ju"><header class="juia-head"><div class="juia-avatar">✂️</div><div class="juia-head-copy"><strong>JuIA • Assistente da Barbearia</strong><small>● Atendimento online</small></div><button class="juia-close" aria-label="Fechar">×</button></header><div class="juia-messages"></div><div class="juia-quick"><button class="juia-chip">Quero agendar</button><button class="juia-chip">Serviços e preços</button><button class="juia-chip">Horários</button><button class="juia-chip">Localização</button><button class="juia-chip">Minha fidelidade</button></div><div class="juia-handoff"><a href="${WA}" target="_blank" rel="noopener">Prefere atendimento humano? Fale com o Juliano →</a></div><form class="juia-form"><div class="juia-input-row"><input class="juia-input" maxlength="500" autocomplete="off" placeholder="Digite sua mensagem..." aria-label="Mensagem"><button class="juia-send" aria-label="Enviar">➤</button></div><small class="juia-privacy">Ao conversar, você concorda com o uso dos dados apenas para atendimento e agendamento.</small></form></section>`;
  document.body.insertAdjacentHTML('beforeend',html);
  const chat=document.querySelector('.juia-chat'),messages=document.querySelector('.juia-messages'),input=document.querySelector('.juia-input');
  function add(text,role='bot',actions=[]){const el=document.createElement('div');el.className=`juia-msg ${role}`;el.textContent=text;if(actions.length){const box=document.createElement('div');box.className='juia-actions';actions.forEach(a=>{const b=document.createElement(a.url?'a':'button');b.className=`juia-action ${a.primary?'primary':''}`;b.textContent=a.label;if(a.url){b.href=a.url;b.target='_blank';b.rel='noopener'}else b.onclick=()=>send(a.message||a.label);box.appendChild(b)});el.appendChild(box)}messages.appendChild(el);messages.scrollTop=messages.scrollHeight;}
  function persist(){sessionStorage.setItem('bdj_juia_state',JSON.stringify(state));sessionStorage.setItem('bdj_juia_history',JSON.stringify(history.slice(-12)));}
  async function send(text){text=String(text||input.value).trim();if(!text)return;input.value='';add(text,'user');history.push({role:'user',content:text});persist();const typing=document.createElement('div');typing.className='juia-typing';typing.textContent='JuIA está verificando...';messages.appendChild(typing);messages.scrollTop=messages.scrollHeight;try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','apikey':cfg.supabaseAnonKey},body:JSON.stringify({session_id:sid,message:text,state,history:history.slice(-10),page:location.pathname})});const data=await r.json();typing.remove();if(!r.ok)throw new Error(data.error||'Não foi possível responder.');state=data.state||state;history.push({role:'assistant',content:data.reply});persist();const actions=data.actions||[];if(data.handoff)actions.push({label:'Falar com o Juliano',url:WA,primary:true});add(data.reply,'bot',actions);window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:'juia_site_message',juia_intent:data.intent||'unknown'});}catch(e){typing.remove();add('Desculpe, tive uma instabilidade. Você pode tentar novamente ou falar diretamente com o Juliano.','bot is-error',[{label:'Falar com o Juliano',url:WA,primary:true}]);}}
  document.querySelector('.juia-launcher').onclick=()=>{chat.classList.add('is-open');document.body.classList.add('juia-open');setTimeout(()=>input.focus({preventScroll:true}),60);window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:'juia_site_open'});if(!history.length)add('Olá! Sou a JuIA, assistente virtual da Barbearia do Ju. Posso informar preços, sugerir serviços e produtos, consultar fidelidade e fazer seu agendamento. Como posso ajudar? 😊');};
  const closeChat=()=>{chat.classList.remove('is-open');document.body.classList.remove('juia-open');document.querySelector('.juia-launcher')?.focus({preventScroll:true});};document.querySelector('.juia-close').onclick=closeChat;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&chat.classList.contains('is-open'))closeChat()});
  document.querySelector('.juia-form').onsubmit=e=>{e.preventDefault();send()};
  document.querySelectorAll('.juia-chip').forEach(b=>b.onclick=()=>send(b.textContent));
})();
