// v29.143.0 — virou módulo pra importar a regra das famílias (1 corte + 1 barba por
// atendimento, fonte única em assets/js/service-rules.js). Caso real: Sabrino, 06/09/2026,
// abriu o link de reagendamento de um cancelamento de agosto, a página pré-marcou
// "Corte de cabelo" e "Barba Express" (o serviço anterior, desmontado), ele clicou em
// "Corte + Barba Express" e a página aceitou os dois cortes — saiu "Corte de cabelo +
// Corte + Barba Express", 80 min. O carrinho do site já impedia isso desde a v29.62.0;
// esta página tinha ficado de fora.
import { applyServiceRule, normalizeServiceSet, splitServiceNames } from './assets/js/service-rules.js?v=29.62.0';
const cfg=window.BDJ_AGENDA_CONFIG||{},sb=(cfg.supabaseUrl&&cfg.supabaseAnonKey)?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null,$=id=>document.getElementById(id),money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),params=new URLSearchParams(location.search),code=params.get('code')||'',token=params.get('token')||'';
// Catálogo único em products-catalog-v1.js — só entram aqui os produtos com `for`
// não-vazio (mesmo recorte de agenda-v15.js), catálogo completo (bebidas etc.) fica
// só pro balcão/admin.
const all=window.BDJ_SERVICES||[],productCatalog=(window.BDJ_PRODUCTS||[]).filter(p=>Array.isArray(p.for)&&p.for.length);let source,services=[],products=[],selectedTime='',step=1;
const total=()=>({duration:services.reduce((a,s)=>a+Number(s.duration),0),service:services.reduce((a,s)=>a+Number(s.price),0),products:products.reduce((a,s)=>a+Number(s.price),0)}),addMin=(t,m)=>{let[a,b]=t.split(':').map(Number),d=new Date(2000,0,1,a,b+m);return`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`};
// Mesmo aviso (texto e visual) do agenda-v15.js: explica a troca/recusa em português simples.
function ruleNotice(message){let el=$('rebook-rule-notice');if(!el){el=document.createElement('p');el.id='rebook-rule-notice';el.setAttribute('role','status');el.style.cssText='margin:0 0 .75rem;padding:.65rem .9rem;border-radius:10px;background:#fff7e6;color:#5a3d00;border:1px solid #f0d9a6;font-size:.95rem;line-height:1.35';$('rebook-services')?.insertAdjacentElement('beforebegin',el)}el.textContent=message||'';el.hidden=!message}
function renderServices(){ $('rebook-services').innerHTML=all.map((s,i)=>`<button type="button" class="rebooking-option ${services.some(x=>x.name===s.name)?'is-selected':''}" data-service="${i}"><span>${services.some(x=>x.name===s.name)?'✓':'＋'}</span><div><strong>${s.name}</strong><small>${s.duration} min · ${money(s.price)}</small></div></button>`).join('');update() }
function renderProducts(){ $('rebook-products').innerHTML=productCatalog.map((p,i)=>`<button type="button" class="rebooking-option ${products.some(x=>x.name===p.name)?'is-selected':''}" data-product="${i}"><span>${products.some(x=>x.name===p.name)?'✓':'＋'}</span><div><strong>${p.name}</strong><small>${money(p.price)}</small></div></button>`).join('') }
function update(){const t=total(),date=$('rebook-date').value;let html=`<ul class="agenda-summary-services">${services.map(s=>`<li><span>${s.name}</span><b>${money(s.price)}</b></li>`).join('')}</ul>`;if(products.length)html+=`<p class="eyebrow summary-subtitle">Produtos</p><ul class="agenda-summary-services">${products.map(p=>`<li><span>${p.name}</span><b>${money(p.price)}</b></li>`).join('')}</ul>`;html+=`<div class="booking-summary-total"><span>Total estimado</span><strong>${money(t.service+t.products)}</strong></div><p class="booking-summary-duration">Atendimento: <strong>${t.duration} min</strong></p>`;if(date)html+=`<div class="booking-summary-date"><span>Data</span><strong>${new Date(date+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}</strong></div>`;if(selectedTime)html+=`<div class="booking-summary-time"><span>Horário</span><strong>${selectedTime} às ${addMin(selectedTime,t.duration)}</strong></div>`;$('rebook-summary').innerHTML=html;$('rebook-review').innerHTML=html;document.querySelector('[data-next="2"]').disabled=!services.length;document.querySelector('[data-next="3"]').disabled=!selectedTime}
async function slots(){selectedTime='';update();let d=$('rebook-date').value,b=$('rebook-slots');b.innerHTML='<div class="booking-slots-loading">Consultando horários…</div>';if(!d||!services.length)return;const {data,error}=await sb.rpc('get_available_slots',{p_date:d,p_duration_minutes:total().duration});if(error){b.innerHTML='<div class="booking-empty-note">Não foi possível consultar.</div>';return}const list=(data||[]).map(x=>String(x.slot_time).slice(0,5));$('rebook-day-message').textContent=list.length?`${list.length} horários disponíveis`:'Sem horários nessa data';b.innerHTML='';if(!list.length)b.innerHTML='<div class="booking-empty-note"><strong>Sem vagas nessa data.</strong><small>Escolha outro dia.</small></div>';list.forEach(time=>{let x=document.createElement('button');x.className='agenda-slot';x.innerHTML=`<strong>${time}</strong><small>disponível</small>`;x.onclick=()=>{b.querySelectorAll('button').forEach(y=>y.classList.remove('is-selected'));x.classList.add('is-selected');selectedTime=time;update()};b.appendChild(x)})}
function go(n){if(n===2&&!services.length)return;if(n===3&&!selectedTime)return;step=n;document.querySelectorAll('[data-step]').forEach(x=>x.hidden=Number(x.dataset.step)!==n);document.querySelectorAll('[data-go]').forEach(x=>x.classList.toggle('is-active',Number(x.dataset.go)===n));update();scrollTo({top:0,behavior:'smooth'})}
async function submit(){let btn=$('rebook-submit');btn.disabled=true;btn.textContent='Confirmando…';const {data,error}=await sb.functions.invoke('create-rebooking',{body:{code,token,services:services.map(s=>s.name),selected_products:products,booking_date:$('rebook-date').value,start_time:selectedTime,notes:$('rebook-notes').value}});if(error||!data?.ok){alert(data?.error||error?.message||'Não foi possível reagendar.');btn.disabled=false;btn.textContent='Confirmar novo agendamento';await slots();return}document.querySelectorAll('.rebooking-step').forEach(x=>x.hidden=true);$('rebooking-success').hidden=false;$('rebook-manage').href=data.manage_url;document.querySelector('.rebooking-summary').hidden=true;scrollTo({top:0,behavior:'smooth'})}
// O serviço anterior é desmontado nos nomes do catálogo (splitServiceNames não confunde o
// " + " dos combos com o separador) e normalizado: dentro de cada família fica só o mais
// completo. "Corte de cabelo + Barba Express" volta como esses dois; se um combo já cobrir
// o outro item, o item some.
function preselectFromSource(name){const known=all.map(s=>s.name);const exact=all.find(s=>s.name===name);if(exact)return[exact];let picked=splitServiceNames(name,known).map(n=>all.find(s=>s.name===n)).filter(Boolean);if(!picked.length)picked=all.filter(s=>String(name).includes(s.name));return normalizeServiceSet(picked).items}
async function init(){const {data,error}=await sb.functions.invoke('rebooking-context',{body:{code,token}});$('rebooking-loading').hidden=true;if(error||!data?.ok){$('rebooking-error').hidden=false;$('rebooking-error-text').textContent=data?.error||error?.message||'Link inválido.';return}source=data.booking;$('rebooking-app').hidden=false;$('old-booking').textContent=`${source.service_name} · ${source.booking_date.split('-').reverse().join('/')} às ${source.start_time}`;$('customer-info').textContent=`${source.customer_name} · ${source.customer_phone}${source.customer_email?' · '+source.customer_email:''}`;$('rebook-notes').value=source.notes||'';services=preselectFromSource(String(source.service_name||''));products=(source.selected_products||[]).map(p=>productCatalog.find(x=>x.name===p.name)).filter(Boolean);$('rebook-date').min=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date());$('rebook-date').value='';renderServices();renderProducts();go(1)}
document.addEventListener('click',e=>{let s=e.target.closest('[data-service]');if(s){let item=all[Number(s.dataset.service)],i=services.findIndex(x=>x.name===item.name);if(i>=0){services.splice(i,1);ruleNotice('')}else{const rule=applyServiceRule(services.map(x=>x.name),item.name);ruleNotice(rule.message);if(!rule.added)return;services=services.filter(x=>rule.services.includes(x.name));services.push(item)}selectedTime='';renderServices();return}let p=e.target.closest('[data-product]');if(p){let item=productCatalog[Number(p.dataset.product)],i=products.findIndex(x=>x.name===item.name);i>=0?products.splice(i,1):products.push(item);renderProducts();update();return}let n=e.target.closest('[data-next]');if(n)go(Number(n.dataset.next));let v=e.target.closest('[data-prev]');if(v)go(Number(v.dataset.prev));let g=e.target.closest('[data-go]');if(g&&Number(g.dataset.go)<=step)go(Number(g.dataset.go))});$('rebook-date').onchange=slots;$('rebook-submit').onclick=submit;init();
