-- JuIA Chat do site — execute uma vez no SQL Editor do Supabase.
create table if not exists public.site_chat_messages (
 id bigint generated by default as identity primary key,
 session_id text not null,
 role text not null check (role in ('user','assistant')),
 content text not null,
 intent text,
 state jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);
create index if not exists site_chat_messages_session_idx on public.site_chat_messages(session_id,created_at desc);
alter table public.site_chat_messages enable row level security;
revoke all on public.site_chat_messages from public,anon,authenticated;
grant select,insert on public.site_chat_messages to service_role;
grant execute on function public.get_available_slots(date,integer) to service_role;
grant execute on function public.create_public_booking_v15(text,text,text,text,numeric,integer,date,time,text,jsonb) to service_role;
