-- Barbearia OS V21 — fidelidade digital, catálogo comercial e fila de e-mails.
-- Execute uma única vez no SQL Editor do Supabase.

create table if not exists public.loyalty_accounts (
  customer_id uuid primary key references public.customer_profiles(id) on delete cascade,
  points integer not null default 0 check (points >= 0),
  rewards_available integer not null default 0 check (rewards_available >= 0),
  lifetime_points integer not null default 0 check (lifetime_points >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.loyalty_events (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.customer_profiles(id) on delete cascade,
  booking_id uuid references public.bookings(id) on delete set null,
  event_type text not null check (event_type in ('earn','redeem','adjustment')),
  points_delta integer not null,
  description text,
  created_at timestamptz not null default now()
);
create unique index if not exists loyalty_one_earn_per_booking
  on public.loyalty_events(booking_id,event_type)
  where booking_id is not null and event_type='earn';

create table if not exists public.email_outbox (
  id bigint generated by default as identity primary key,
  booking_id uuid references public.bookings(id) on delete cascade,
  recipient text not null,
  template text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending','sent','failed','cancelled')),
  attempts integer not null default 0,
  scheduled_for timestamptz not null default now(),
  sent_at timestamptz,
  last_error text,
  created_at timestamptz not null default now()
);
create index if not exists email_outbox_pending_idx on public.email_outbox(status,scheduled_for);

alter table public.loyalty_accounts enable row level security;
alter table public.loyalty_events enable row level security;
alter table public.email_outbox enable row level security;
grant select,update on public.loyalty_accounts to authenticated;
grant select on public.loyalty_events to authenticated;
grant select on public.email_outbox to authenticated;
grant select,insert,update,delete on public.loyalty_accounts,public.loyalty_events,public.email_outbox to service_role;

drop policy if exists "admin read loyalty accounts" on public.loyalty_accounts;
drop policy if exists "admin update loyalty accounts" on public.loyalty_accounts;
drop policy if exists "admin read loyalty events" on public.loyalty_events;
drop policy if exists "admin read email outbox" on public.email_outbox;
create policy "admin read loyalty accounts" on public.loyalty_accounts for select to authenticated using (true);
create policy "admin update loyalty accounts" on public.loyalty_accounts for update to authenticated using (true) with check (true);
create policy "admin read loyalty events" on public.loyalty_events for select to authenticated using (true);
create policy "admin read email outbox" on public.email_outbox for select to authenticated using (true);

create or replace function public.v21_sync_loyalty_on_completed_booking()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_customer uuid; v_points integer; v_rewards integer;
begin
  if new.status='completed' and coalesce(old.status,'') <> 'completed'
     and lower(new.service_name) like '%corte%' then
    select id into v_customer from public.customer_profiles
      where phone=regexp_replace(new.customer_phone,'\\D','','g') and archived=false limit 1;
    if v_customer is not null then
      insert into public.loyalty_accounts(customer_id) values(v_customer)
        on conflict(customer_id) do nothing;
      insert into public.loyalty_events(customer_id,booking_id,event_type,points_delta,description)
        values(v_customer,new.id,'earn',1,'Corte concluído')
        on conflict do nothing;
      if found then
        update public.loyalty_accounts
          set points=points+1,lifetime_points=lifetime_points+1,updated_at=now()
          where customer_id=v_customer
          returning points,rewards_available into v_points,v_rewards;
        if v_points >= 10 then
          update public.loyalty_accounts
            set points=points-10,rewards_available=rewards_available+1,updated_at=now()
            where customer_id=v_customer;
        end if;
      end if;
    end if;
  end if;
  return new;
end $$;
drop trigger if exists bookings_v21_loyalty on public.bookings;
create trigger bookings_v21_loyalty after update of status on public.bookings
for each row execute function public.v21_sync_loyalty_on_completed_booking();

create or replace function public.v21_queue_booking_email()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if nullif(trim(new.customer_email),'') is not null then
    if tg_op='INSERT' then
      insert into public.email_outbox(booking_id,recipient,template,payload)
      values(new.id,lower(trim(new.customer_email)),'booking_received',jsonb_build_object('name',new.customer_name,'date',new.booking_date,'time',new.start_time,'services',new.service_name));
    elsif new.status is distinct from old.status then
      insert into public.email_outbox(booking_id,recipient,template,payload)
      values(new.id,lower(trim(new.customer_email)),'booking_status',jsonb_build_object('name',new.customer_name,'status',new.status,'date',new.booking_date,'time',new.start_time,'services',new.service_name));
    end if;
  end if;
  return new;
end $$;
drop trigger if exists bookings_v21_email_queue on public.bookings;
create trigger bookings_v21_email_queue after insert or update of status on public.bookings
for each row execute function public.v21_queue_booking_email();

create or replace function public.get_customer_commercial_context(p_phone text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_phone text:=regexp_replace(p_phone,'\\D','','g'); v_result jsonb;
begin
 select jsonb_build_object(
   'customer_id',c.id,'name',c.name,'email',c.email,'birth_date',c.birth_date,
   'points',coalesce(l.points,0),'rewards_available',coalesce(l.rewards_available,0),
   'completed_visits',(select count(*) from public.bookings b where regexp_replace(b.customer_phone,'\\D','','g')=v_phone and b.status='completed'),
   'last_services',(select b.service_name from public.bookings b where regexp_replace(b.customer_phone,'\\D','','g')=v_phone and b.status='completed' order by b.booking_date desc,b.start_time desc limit 1),
   'last_visit',(select b.booking_date from public.bookings b where regexp_replace(b.customer_phone,'\\D','','g')=v_phone and b.status='completed' order by b.booking_date desc,b.start_time desc limit 1),
   'last_products',(select b.selected_products from public.bookings b where regexp_replace(b.customer_phone,'\\D','','g')=v_phone and jsonb_array_length(coalesce(b.selected_products,'[]'::jsonb))>0 order by b.booking_date desc limit 1)
 ) into v_result
 from public.customer_profiles c left join public.loyalty_accounts l on l.customer_id=c.id
 where c.phone=v_phone and c.archived=false limit 1;
 return coalesce(v_result,'{}'::jsonb);
end $$;
grant execute on function public.get_customer_commercial_context(text) to service_role,authenticated;

-- Cria contas de fidelidade para clientes existentes.
insert into public.loyalty_accounts(customer_id)
select id from public.customer_profiles where archived=false
on conflict(customer_id) do nothing;
