-- V27.1 — Experiência pós-atendimento + CRM inteligente.
-- Seguro para reexecução.

create extension if not exists pgcrypto;

create table if not exists public.experience_requests (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null unique references public.bookings(id) on delete cascade,
  customer_id uuid references public.customer_profiles(id) on delete set null,
  token uuid not null unique default gen_random_uuid(),
  status text not null default 'pending' check (status in ('pending','sent','opened','satisfied','feedback','review_clicked','expired','failed')),
  scheduled_for timestamptz not null,
  sent_at timestamptz,
  opened_at timestamptz,
  responded_at timestamptz,
  review_clicked_at timestamptz,
  feedback_text text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists experience_requests_due_idx
  on public.experience_requests(status, scheduled_for);
create index if not exists experience_requests_customer_idx
  on public.experience_requests(customer_id, created_at desc);

create table if not exists public.customer_timeline (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.customer_profiles(id) on delete cascade,
  booking_id uuid references public.bookings(id) on delete set null,
  event_type text not null,
  title text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists customer_timeline_customer_idx
  on public.customer_timeline(customer_id, created_at desc);

alter table public.experience_requests enable row level security;
alter table public.customer_timeline enable row level security;

grant select on public.experience_requests, public.customer_timeline to authenticated;
grant select,insert,update,delete on public.experience_requests, public.customer_timeline to service_role;

drop policy if exists "admin read experience requests" on public.experience_requests;
drop policy if exists "admin read customer timeline" on public.customer_timeline;
create policy "admin read experience requests" on public.experience_requests
  for select to authenticated using (true);
create policy "admin read customer timeline" on public.customer_timeline
  for select to authenticated using (true);

create or replace function public.v27_customer_for_booking(p_booking public.bookings)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_customer uuid;
begin
  select id into v_customer
  from public.customer_profiles
  where regexp_replace(phone,'\D','','g')=regexp_replace(p_booking.customer_phone,'\D','','g')
    and archived=false
  limit 1;
  return v_customer;
end $$;

create or replace function public.v27_queue_experience_after_completion()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_customer uuid;
begin
  if new.status='completed' and coalesce(old.status,'') <> 'completed' then
    v_customer := public.v27_customer_for_booking(new);

    insert into public.customer_timeline(customer_id,booking_id,event_type,title,details)
    values(v_customer,new.id,'booking_completed','Atendimento concluído',jsonb_build_object(
      'services',new.service_name,
      'value',coalesce(new.service_price,0)+coalesce(new.products_price,0),
      'date',new.booking_date,
      'time',new.start_time
    ));

    if nullif(trim(new.customer_email),'') is not null then
      insert into public.experience_requests(booking_id,customer_id,scheduled_for)
      values(new.id,v_customer,now()+interval '2 hours')
      on conflict(booking_id) do update set
        customer_id=excluded.customer_id,
        scheduled_for=excluded.scheduled_for,
        status=case when public.experience_requests.status in ('failed','expired') then 'pending' else public.experience_requests.status end,
        last_error=null,
        updated_at=now();
    end if;
  end if;
  return new;
end $$;

drop trigger if exists bookings_v27_experience on public.bookings;
create trigger bookings_v27_experience
  after update of status on public.bookings
  for each row execute function public.v27_queue_experience_after_completion();

create or replace function public.get_experience_context(p_token uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_result jsonb;
begin
  update public.experience_requests
    set opened_at=coalesce(opened_at,now()),
        status=case when status='sent' then 'opened' else status end,
        updated_at=now()
  where token=p_token and status not in ('expired','failed');

  select jsonb_build_object(
    'valid',true,
    'status',e.status,
    'first_name',split_part(trim(b.customer_name),' ',1),
    'booking_date',b.booking_date,
    'services',b.service_name,
    'feedback_text',e.feedback_text
  ) into v_result
  from public.experience_requests e
  join public.bookings b on b.id=e.booking_id
  where e.token=p_token
    and e.created_at > now()-interval '30 days';

  return coalesce(v_result,jsonb_build_object('valid',false));
end $$;

revoke all on function public.get_experience_context(uuid) from public;
grant execute on function public.get_experience_context(uuid) to anon,authenticated,service_role;

create or replace function public.submit_experience_response(
  p_token uuid,
  p_response text,
  p_feedback text default null
) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_req public.experience_requests%rowtype; v_title text;
begin
  select * into v_req from public.experience_requests
  where token=p_token and created_at > now()-interval '30 days'
  for update;
  if v_req.id is null then return jsonb_build_object('ok',false,'error','Link inválido ou expirado.'); end if;

  if p_response='satisfied' then
    update public.experience_requests set status='satisfied',responded_at=now(),updated_at=now() where id=v_req.id;
    v_title:='Cliente informou que ficou satisfeito';
  elsif p_response='feedback' then
    if char_length(trim(coalesce(p_feedback,''))) < 3 then
      return jsonb_build_object('ok',false,'error','Escreva uma breve sugestão.');
    end if;
    update public.experience_requests set status='feedback',feedback_text=left(trim(p_feedback),2000),responded_at=now(),updated_at=now() where id=v_req.id;
    v_title:='Sugestão privada recebida';
  elsif p_response='review_clicked' then
    update public.experience_requests set status='review_clicked',review_clicked_at=now(),updated_at=now() where id=v_req.id;
    v_title:='Cliente abriu a avaliação do Google';
  else
    return jsonb_build_object('ok',false,'error','Resposta inválida.');
  end if;

  insert into public.customer_timeline(customer_id,booking_id,event_type,title,details)
  values(v_req.customer_id,v_req.booking_id,p_response,v_title,
    case when p_response='feedback' then jsonb_build_object('feedback',left(trim(p_feedback),2000)) else '{}'::jsonb end);

  return jsonb_build_object('ok',true,'status',p_response);
end $$;

revoke all on function public.submit_experience_response(uuid,text,text) from public;
grant execute on function public.submit_experience_response(uuid,text,text) to anon,authenticated,service_role;

create or replace view public.v27_customer_metrics as
select
  c.id as customer_id,
  c.name,
  c.phone,
  c.email,
  count(b.id) filter(where b.status='completed')::integer as completed_visits,
  coalesce(sum(coalesce(b.service_price,0)+coalesce(b.products_price,0)) filter(where b.status='completed'),0)::numeric as total_spent,
  coalesce(avg(coalesce(b.service_price,0)+coalesce(b.products_price,0)) filter(where b.status='completed'),0)::numeric as average_ticket,
  max(b.booking_date) filter(where b.status='completed') as last_visit,
  coalesce(l.points,0) as loyalty_points,
  coalesce(l.rewards_available,0) as rewards_available,
  count(e.id) filter(where e.status='feedback')::integer as private_feedbacks,
  count(e.id) filter(where e.status='review_clicked')::integer as review_clicks
from public.customer_profiles c
left join public.bookings b on regexp_replace(b.customer_phone,'\D','','g')=regexp_replace(c.phone,'\D','','g')
left join public.loyalty_accounts l on l.customer_id=c.id
left join public.experience_requests e on e.customer_id=c.id
group by c.id,l.points,l.rewards_available;

grant select on public.v27_customer_metrics to authenticated,service_role;
