-- Barbearia do Ju — V27.1 CRM Premium + experiência pós-atendimento
-- Execute uma vez no SQL Editor do Supabase. Seguro para reexecução.

create extension if not exists pgcrypto;

alter table public.customer_profiles
  add column if not exists beverage_preference text,
  add column if not exists care_notes text,
  add column if not exists conversation_notes text,
  add column if not exists google_reviewed boolean not null default false,
  add column if not exists google_reviewed_at timestamptz,
  add column if not exists satisfaction_status text,
  add column if not exists satisfaction_updated_at timestamptz;

create table if not exists public.customer_timeline (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.customer_profiles(id) on delete cascade,
  booking_id uuid references public.bookings(id) on delete set null,
  event_type text not null,
  title text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists customer_timeline_customer_date_idx
  on public.customer_timeline(customer_id, created_at desc);

create table if not exists public.experience_requests (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references public.bookings(id) on delete cascade,
  customer_id uuid references public.customer_profiles(id) on delete set null,
  token uuid not null default gen_random_uuid() unique,
  customer_name text not null,
  customer_email text not null,
  scheduled_for timestamptz not null default (now() + interval '2 hours'),
  sent_at timestamptz,
  opened_at timestamptz,
  answered_at timestamptz,
  answer text check (answer is null or answer in ('satisfied','suggestion')),
  feedback text,
  google_clicked_at timestamptz,
  status text not null default 'pending' check (status in ('pending','sent','answered','failed','cancelled')),
  attempts integer not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(booking_id)
);

create index if not exists experience_requests_due_idx
  on public.experience_requests(status, scheduled_for)
  where status='pending';

alter table public.customer_timeline enable row level security;
alter table public.experience_requests enable row level security;

grant select,insert,update,delete on public.customer_timeline to authenticated;
grant select,update on public.experience_requests to authenticated;
grant select,insert,update,delete on public.customer_timeline,public.experience_requests to service_role;

drop policy if exists "admin timeline all" on public.customer_timeline;
create policy "admin timeline all" on public.customer_timeline for all to authenticated using (true) with check (true);
drop policy if exists "admin experience read" on public.experience_requests;
create policy "admin experience read" on public.experience_requests for select to authenticated using (true);
drop policy if exists "admin experience update" on public.experience_requests;
create policy "admin experience update" on public.experience_requests for update to authenticated using (true) with check (true);

create or replace function public.v27_customer_id_by_phone(p_phone text)
returns uuid language sql stable security definer set search_path=public as $$
  select id from public.customer_profiles
  where regexp_replace(phone,'\D','','g')=regexp_replace(p_phone,'\D','','g')
  order by archived asc, updated_at desc limit 1
$$;

create or replace function public.v27_queue_experience_on_completion()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_customer uuid;
begin
  if new.status='completed' and coalesce(old.status,'') <> 'completed' then
    v_customer:=public.v27_customer_id_by_phone(new.customer_phone);
    if v_customer is not null then
      insert into public.customer_timeline(customer_id,booking_id,event_type,title,details)
      values(v_customer,new.id,'attendance_completed','Atendimento concluído',jsonb_build_object('services',new.service_name,'value',coalesce(new.service_price,0)+coalesce(new.products_price,0)));
    end if;
    if nullif(trim(coalesce(new.customer_email,'')),'') is not null then
      insert into public.experience_requests(booking_id,customer_id,customer_name,customer_email,scheduled_for)
      values(new.id,v_customer,new.customer_name,lower(trim(new.customer_email)),now()+interval '2 hours')
      on conflict(booking_id) do nothing;
    end if;
  end if;
  return new;
end $$;

drop trigger if exists bookings_v27_experience on public.bookings;
create trigger bookings_v27_experience after update of status on public.bookings
for each row execute function public.v27_queue_experience_on_completion();

create or replace function public.get_experience_context(p_token uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare r public.experience_requests; b public.bookings;
begin
  select * into r from public.experience_requests where token=p_token;
  if r.id is null then return jsonb_build_object('ok',false,'error','Link inválido.'); end if;
  select * into b from public.bookings where id=r.booking_id;
  update public.experience_requests set opened_at=coalesce(opened_at,now()),updated_at=now() where id=r.id;
  return jsonb_build_object('ok',true,'first_name',split_part(trim(r.customer_name),' ',1),'booking_date',b.booking_date,'service_name',b.service_name,'answered',r.answered_at is not null,'answer',r.answer);
end $$;

create or replace function public.submit_experience_response(p_token uuid,p_answer text,p_feedback text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare r public.experience_requests;
begin
  if p_answer not in ('satisfied','suggestion') then raise exception 'Resposta inválida.'; end if;
  select * into r from public.experience_requests where token=p_token for update;
  if r.id is null then return jsonb_build_object('ok',false,'error','Link inválido.'); end if;
  if r.answered_at is not null then return jsonb_build_object('ok',true,'already_answered',true,'answer',r.answer); end if;
  if p_answer='suggestion' and char_length(trim(coalesce(p_feedback,'')))<3 then raise exception 'Conte brevemente o que podemos melhorar.'; end if;
  update public.experience_requests set answer=p_answer,feedback=nullif(trim(p_feedback),''),answered_at=now(),status='answered',updated_at=now() where id=r.id;
  if r.customer_id is not null then
    update public.customer_profiles set satisfaction_status=p_answer,satisfaction_updated_at=now(),updated_at=now() where id=r.customer_id;
    insert into public.customer_timeline(customer_id,booking_id,event_type,title,details)
    values(r.customer_id,r.booking_id,case when p_answer='satisfied' then 'satisfaction_positive' else 'feedback_private' end,
      case when p_answer='satisfied' then 'Cliente informou que ficou satisfeito' else 'Cliente enviou uma sugestão privada' end,
      jsonb_build_object('feedback',nullif(trim(p_feedback),'')));
  end if;
  return jsonb_build_object('ok',true,'answer',p_answer);
end $$;

create or replace function public.mark_experience_google_click(p_token uuid)
returns boolean language plpgsql security definer set search_path=public as $$
declare v_customer uuid; v_booking uuid;
begin
  update public.experience_requests set google_clicked_at=coalesce(google_clicked_at,now()),updated_at=now()
  where token=p_token returning customer_id,booking_id into v_customer,v_booking;
  if v_customer is not null then
    update public.customer_profiles set google_reviewed=true,google_reviewed_at=coalesce(google_reviewed_at,now()),updated_at=now() where id=v_customer;
    insert into public.customer_timeline(customer_id,booking_id,event_type,title)
    values(v_customer,v_booking,'google_review_click','Cliente abriu a página de avaliação do Google');
  end if;
  return found;
end $$;

revoke all on function public.get_experience_context(uuid) from public;
revoke all on function public.submit_experience_response(uuid,text,text) from public;
revoke all on function public.mark_experience_google_click(uuid) from public;
grant execute on function public.get_experience_context(uuid) to anon,authenticated,service_role;
grant execute on function public.submit_experience_response(uuid,text,text) to anon,authenticated,service_role;
grant execute on function public.mark_experience_google_click(uuid) to anon,authenticated,service_role;

create or replace function public.admin_customer_insights_v27()
returns table(
 customer_id uuid,name text,phone text,email text,completed_visits bigint,total_spent numeric,ticket_average numeric,
 last_visit date,days_inactive integer,average_interval numeric,next_expected date,loyalty_points integer,rewards_available integer,
 ju_score integer,segment text,google_reviewed boolean,satisfaction_status text
) language sql stable security definer set search_path=public as $$
with completed as (
 select c.id customer_id,b.booking_date,(coalesce(b.service_price,0)+coalesce(b.products_price,0))::numeric amount,
 lag(b.booking_date) over(partition by c.id order by b.booking_date,b.start_time) prev_date
 from public.customer_profiles c left join public.bookings b
 on regexp_replace(b.customer_phone,'\D','','g')=regexp_replace(c.phone,'\D','','g') and b.status='completed'
 where c.archived=false
), agg as (
 select customer_id,count(booking_date) completed_visits,coalesce(sum(amount),0) total_spent,max(booking_date) last_visit,
 avg((booking_date-prev_date)) filter(where prev_date is not null) average_interval from completed group by customer_id
)
select c.id,c.name,c.phone,c.email,coalesce(a.completed_visits,0),coalesce(a.total_spent,0),
 case when coalesce(a.completed_visits,0)>0 then round(a.total_spent/a.completed_visits,2) else 0 end,
 a.last_visit,case when a.last_visit is null then null else current_date-a.last_visit end,
 round(coalesce(a.average_interval,c.return_interval_days,30),1),
 case when a.last_visit is null then null else a.last_visit+round(coalesce(a.average_interval,c.return_interval_days,30))::int end,
 coalesce(l.points,0),coalesce(l.rewards_available,0),
 least(100,greatest(0,(coalesce(a.completed_visits,0)*6 + least(25,coalesce(a.total_spent,0)/40) + case when c.google_reviewed then 12 else 0 end + case when coalesce(l.rewards_available,0)>0 then 8 else 0 end - case when a.last_visit is not null and current_date-a.last_visit>60 then 18 else 0 end)::int)),
 case when coalesce(a.total_spent,0)>=1200 or coalesce(a.completed_visits,0)>=18 then 'Platinum'
      when coalesce(a.total_spent,0)>=700 or coalesce(a.completed_visits,0)>=10 then 'Gold'
      when coalesce(a.total_spent,0)>=300 or coalesce(a.completed_visits,0)>=5 then 'Silver' else 'Bronze' end,
 c.google_reviewed,c.satisfaction_status
from public.customer_profiles c left join agg a on a.customer_id=c.id left join public.loyalty_accounts l on l.customer_id=c.id
where c.archived=false order by coalesce(a.last_visit,date '1900-01-01') desc;
$$;
grant execute on function public.admin_customer_insights_v27() to authenticated,service_role;

notify pgrst, 'reload schema';
