-- Barbearia do Ju — V28.4.1
-- Corrige regressões introduzidas na V28.3.0 (satisfação via WhatsApp):
--
-- 1) find_pending_experience_by_phone não tinha limite de 30 dias como
--    get_experience_context/submit_experience_response já têm — cliente que
--    nunca respondia a pesquisa ficava com toda mensagem futura interceptada
--    pela pesquisa pra sempre, impedindo-o de falar com a JuIA ou agendar.
--
-- 2) Nova tabela notification_log: registra qualquer notificação de
--    agendamento enviada (WhatsApp, e-mail ou SMS) pra permitir checagem de
--    duplicidade independente do canal. O lembrete de 24h antes só checava
--    email_queue/sms_queue, então podia reenviar o lembrete por WhatsApp
--    repetidamente (o cron roda a cada 15 min).

create or replace function public.find_pending_experience_by_phone(p_phone text)
returns table(id uuid, token uuid, status text, customer_id uuid, booking_id uuid, customer_name text)
language sql security definer set search_path=public as $$
  select e.id, e.token, e.status, e.customer_id, e.booking_id, b.customer_name
  from public.experience_requests e
  join public.bookings b on b.id = e.booking_id
  where (e.status in ('sent','opened') or (e.status='feedback' and e.feedback is null))
    and e.created_at > now() - interval '30 days'
    and right(regexp_replace(b.customer_phone,'\D','','g'), 11) = right(regexp_replace(p_phone,'\D','','g'), 11)
  order by e.created_at desc
  limit 1
$$;

create table if not exists public.notification_log (
  id bigint generated by default as identity primary key,
  booking_id uuid not null references public.bookings(id) on delete cascade,
  event_type text not null,
  channel text not null,
  created_at timestamptz not null default now()
);
create index if not exists notification_log_booking_event_idx on public.notification_log(booking_id, event_type);

alter table public.notification_log enable row level security;
grant select, insert on public.notification_log to service_role;
drop policy if exists "admin read notification log" on public.notification_log;
create policy "admin read notification log" on public.notification_log
  for select to authenticated using (is_admin());

notify pgrst, 'reload schema';
