-- Barbearia do Ju — V28.5.0
-- Base para mensagens proativas ao cliente (reativação de sumidos, aniversário).
-- Registra cada contato proativo enviado, para não repetir (dedup por tipo).

create table if not exists public.customer_outreach_log (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.customer_profiles(id) on delete cascade,
  phone text not null,
  kind text not null,                 -- 'reactivation' | 'birthday'
  channel text not null default 'whatsapp',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists customer_outreach_log_kind_idx
  on public.customer_outreach_log (kind, created_at desc);
create index if not exists customer_outreach_log_customer_idx
  on public.customer_outreach_log (customer_id, kind, created_at desc);

alter table public.customer_outreach_log enable row level security;
grant select, insert on public.customer_outreach_log to service_role;

drop policy if exists "admin read outreach log" on public.customer_outreach_log;
create policy "admin read outreach log" on public.customer_outreach_log
  for select to authenticated using (is_admin());

-- Retorna clientes elegíveis para reativação: ativos, com telefone válido,
-- com ao menos uma visita concluída, ausentes há tempo suficiente e sem
-- contato de reativação recente (cooldown).
-- p_default_days: limiar quando o cliente não tem return_interval_days definido.
-- p_grace_days: dias extras além do return_interval_days antes de considerar sumido.
-- p_cooldown_days: intervalo mínimo entre duas reativações do mesmo cliente.
create or replace function public.customers_due_for_reactivation(
  p_default_days integer default 45,
  p_grace_days integer default 10,
  p_cooldown_days integer default 40
)
returns table(customer_id uuid, name text, phone text, last_visit date, days_since integer)
language sql security definer set search_path=public as $$
  with ultimas as (
    select c.id, c.name, c.phone, c.return_interval_days,
           max(b.booking_date) filter (where b.status='completed') as ultima_visita
    from public.customer_profiles c
    join public.bookings b
      on right(regexp_replace(b.customer_phone,'\D','','g'), 11)
       = right(regexp_replace(c.phone,'\D','','g'), 11)
    where c.archived = false
      and length(regexp_replace(c.phone,'\D','','g')) >= 10
    group by c.id
  )
  select u.id, u.name, u.phone, u.ultima_visita,
         (current_date - u.ultima_visita) as days_since
  from ultimas u
  where u.ultima_visita is not null
    and (current_date - u.ultima_visita) >=
        coalesce(u.return_interval_days + p_grace_days, p_default_days)
    and not exists (
      select 1 from public.customer_outreach_log l
      where l.customer_id = u.id
        and l.kind = 'reactivation'
        and l.created_at > now() - make_interval(days => p_cooldown_days)
    )
  order by u.ultima_visita asc
  limit 100
$$;

grant execute on function public.customers_due_for_reactivation(integer,integer,integer) to service_role;

notify pgrst, 'reload schema';
